### ISSUE TITLE
Come up with ideas about the assessment/challenge for Casper Course

### ISSUE THREAD

**Issue by ShalmaliCL** [casper-network/docs#1015]
Come up with ideas about the assessment/challenge [per module](https://casperlabs.atlassian.net/l/cp/HjBUBy0r). 
Create the cards if required.

**Comment by ShalmaliCL** [comment]
I have added Assessment and Challenge under [Module 1.](https://casperlabs.atlassian.net/l/cp/uKBUqXKC)
@ACStoneCL @ramujin - Please review and advise.

**Comment by ramujin** [comment]
@ShalmaliCL I went through all sections and made revisions. I think Sections 5 and 6 still need work. For Section 5, we're putting too many prerequisite expectations on the developers when this is supposed to be their foremost experience with the platform. Section 6 seems rather useless to be honest... the use cases are good for marketing, but they aren't actually showing a developer why they should choose the blockchain for their development needs. @ACStoneCL any feedback from your end?

**Comment by ramujin** [comment]
I made some edits, but it's generally good. One of the questions was written twice. I'm not sure why that was the case.

**Comment by ShalmaliCL** [comment]
@ramujin - Thank you for your review. I have removed the repeated question.
