### ISSUE TITLE
Internal Training | BD team technical training preparation 

### ISSUE THREAD

**Issue by ShalmaliCL** [casper-network/docs#1016]
Prepare a slide deck for an hour training session, including speaker notes.
Schedule review with L2 engineering principles (Karan, Adam, Jan)
Reference presentation - https://docs.google.com/presentation/d/1VRc4uJHKuvkPbl4k1LV7wXCkXRQGSw6TgKYDLe-kUGw/edit?usp=sharing

**Comment by ACStoneCL** [comment]
@ShalmaliCL and @ramujin When you get the training presentation shaped up, please tag myself, @darthsiroftardis and @hoffmannjan for review prior to the actual training session.

**Comment by ShalmaliCL** [comment]
The presentation is [ here](https://docs.google.com/presentation/d/1Ow5zE6cMvNrKLMInCldkCzDeaoFLsoDchzaV5g3cylM/edit?usp=sharing). 
@darthsiroftardis @ACStoneCL @hoffmannjan - request you to please review and advise.
Thank you!

**Comment by ShalmaliCL** [comment]
BD team requested to add FAQs and example use cases in the presentation. 
A follow-up card is created for this task. https://github.com/casper-network/docs/issues/1013
CC: @ACStoneCL @ramujin
