### ISSUE TITLE
Fix local search

### ISSUE THREAD

**Issue by andrzej-casper** [casper-network/docs#1032]
Once https://github.com/casper-network/docs/issues/1030 is merged - so no hardcoded Algolia will be available - you will notice that search bar disappears for local environment (unless `.env.development` is configured). However, local search might work without relying on 3rd party service - there is plugin `cmfcmf/docusaurus-search-local`, **which is already installed and configured**, but plugin is just not listed in main config.

**Comment by ACStoneCL** [comment]
Search function is not required for local versions.
