### ISSUE TITLE
Archive and restore of a casper node DB with zstd

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#1038]
https://github.com/casper-network/casper-node/wiki/Archive-and-Restore-of-casper-node-DB-with-zstd
docs team to add to docs

**Comment by GuybrushX** [comment]
Please note that there are at least 2 small errors in that link for the "Decompression" part:
https://github.com/casper-network/casper-node/wiki/Archive-and-Restore-of-casper-node-DB-with-zstd#decompression

Here is the mistake:
`-long=31` # Wrong
`--long=31` # Correct

This is wrong in various places across the docs but I didn't find a way on how to suggest a change to a wiki entry. It seems this is a limitation of GitHub.

@sacherjj Can you have a look and fix the commands please?

**Comment by ipopescu** [comment]
@GuybrushX, thanks so much for spotting the mistakes. We have addressed them; they are now in the Casper documentation instead of the wiki.
