### ISSUE TITLE
Casper Wallet integration

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#1062]
The [Casper Wallet](https://www.casperwallet.io) has been launched, replacing the Signer, which will be deprecated. Work completed so far: #1019, #956.

The following documentation in the dApp section needs to be replaced to reference the Casper Wallet:
-  https://docs.casper.network/developers/dapps/signer-integration/
-  https://docs.casper.network/developers/dapps/technology-stack/
- https://docs.casper.network/resources/tutorials/advanced/list-cspr/
- https://docs.casper.network/resources/tutorials/beginner/use-javascript-sdk/

The documentation needs working code and code samples. This is the developer's section for the Casper Wallet: https://www.casperwallet.io/develop.

**Comment by ACStoneCL** [comment]
Work here is done, we will create a new epic to account for updating and integrating Casper Wallet docs.
