### ISSUE TITLE
BD Training Follow-up and Meeting

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1074]
Based on the 4/13 meeting, we need to answer the questions listed [here](https://docs.google.com/document/d/1c8CeYgcnHmqEH-N_RcAIJsgDDj9Nbt4mDp5Mv7gQ3ho/edit).

Once the questions are answered, we can present the information to the BD team.

**Comment by ShalmaliCL** [comment]
Reviewing and updating the responses - https://docs.google.com/document/d/1c8CeYgcnHmqEH-N_RcAIJsgDDj9Nbt4mDp5Mv7gQ3ho/edit?usp=sharing
CC: @ACStoneCL

**Comment by ShalmaliCL** [comment]
Reviewed the documentation. Will schedule a meeting with the BD team and close this ticket.
