### ISSUE TITLE
Document versions of our JSON-RPC server endpoints

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#108]
Get a page up somewhere which documents the various versions of our JSON-RPC server endpoints.  I'm thinking of something like: https://hyperchain.readthedocs.io/en/latest/JSON-RPC_manual.html.
We have the existing ability to automatically generate a schema for our API which is presented in an OpenRPC format, so most of the work here would be just presenting the generated JSON in a decent, human-readable way, and hosting the single page for each version of our API somewhere.

**Comment by ACStoneCL** [comment]
This card is redundant with [roadmap#121](https://github.com/casper-network/roadmap/issues/121), so I'm self-assigning so I can manage it concurrently.

**Comment by devendran-m** [comment]
Closed via #266
