### ISSUE TITLE
Hide empty docs pages from indexing

### ISSUE THREAD

**Issue by Adrian-Wrona** [casper-network/docs#1092]
Examples are:
https://docs.casper.network/resources/support/
https://docs.casper.network/resources/changelog/
https://docs.casper.network/resources/contribute-to-docs/
https://docs.casper.network/developers/dapps/sdk/additional-libraries/

the meta-statement for this is:
<meta name="robots" content=**"noindex, follow"**>
(means: the page may not be indexed, but bots may crawl the page to follow further internal links)

**Comment by ipopescu** [comment]
This card is still relevant and should be a quick win. Re-labeling it.

**Comment by ipopescu** [comment]
This was actually completed.
