### ISSUE TITLE
Change the duplicate HTML titles

### ISSUE THREAD

**Issue by Adrian-Wrona** [casper-network/docs#1093]
There are some URLs that use the same HTML titles. Moreover, these are not very meaningful. 
It makes sense to give the pages (see attached Excel document) descriptive HTML titles - the same as headings of the pages.

[https://app.zenhub.com/files/407502905/65be23c1-536b-4cff-bcde-b485b3a79e88/download](https://app.zenhub.com/files/407502905/65be23c1-536b-4cff-bcde-b485b3a79e88/download)

**Comment by ipopescu** [comment]
I've analyzed the Excel document, and only 2 pages needed new titles. The rest were OK.

<img width="1113" alt="Screenshot 2023-12-22 at 21 52 18" src="https://github.com/casper-network/docs/assets/4185994/5d03d28d-be99-4fe3-880a-92483da36101">
