### ISSUE TITLE
UI changes to the docs (proposed by Scalio)

### ISSUE THREAD

**Issue by Adrian-Wrona** [casper-network/docs#1097]
Change base letter spacing to 0.3px

H1s
- font weight: 400
- line-height: 1.2
- font-size: 64px

Table of contents
- font-size: 14px
- letter-spacing: .3px

menu__link
- padding: 8px 20px
- font-size: 18px
- line-height: 1.25

Attached are the screenshots with the suggestions
[https://app.zenhub.com/files/407502905/53d1cfe3-5b4d-419f-a7c3-4a091874f8e4/download](https://app.zenhub.com/files/407502905/53d1cfe3-5b4d-419f-a7c3-4a091874f8e4/download)

**Comment by ipopescu** [comment]
@Adrian-Wrona is this card still relevant?

**Comment by ipopescu** [comment]
These changes were already addressed by @andrzej-casper.
