### ISSUE TITLE
Interacting with the blockchain using CLI/Overview

### ISSUE THREAD

**Issue by andrzej-casper** [casper-network/docs#1103]
.

**Comment by ipopescu** [comment]
@andrzej-casper @Adrian-Wrona, what are the requirements here, and is this still needed? 
We have an overview page [as part of this PR](https://github.com/casper-network/docs/pull/1240/files#diff-0036d9e7fd308f5f05581e4852cd255b7cc3909781762d8c22d92221881ca181).
