### ISSUE TITLE
Interacting with the blockchain using CLI/Delegate with Casper client

### ISSUE THREAD

**Issue by andrzej-casper** [casper-network/docs#1104]
.

**Comment by ipopescu** [comment]
@Adrian-Wrona @andrzej-casper I think this has been addressed already: https://docs.casper.network/developers/cli/delegate/.

**Comment by ACStoneCL** [comment]
Work is already completed at the page @ipopescu listed.

**Comment by andrzej-casper** [comment]
@ipopescu @ACStoneCL Thanks!
