### ISSUE TITLE
Search seems to be broken?

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/docs#1113]
To replicate search for "bitgo" -> "No results found".

Check that page:
https://docs.casper.network/resources/tutorials/advanced/list-cspr/#the-casper-protocol

"BitGo" is mentioned 2 times -> case doesn't matter, so neither "bitgo" nor "BitGo" are found but are clearly mentioned.

**Comment by GuybrushX** [comment]
I just saw that there are 2 search boxes on the page?

The one powered by "algolia" seems to work, the other one "Search portal" on top and almost in the center is not.

IMO 1 should be removed or it should be very clear what each of the search boxes are doing.

**Comment by ipopescu** [comment]
Thank you, @GuybrushX; several of us agree with you and are working internally on a solution.

**Comment by ACStoneCL** [comment]
Search is now functioning, closing as complete.
