### ISSUE TITLE
Discovery and Planning for Module 1

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1122]
This ticket accounts for work to be done in planning and developing an initial module for the Casper Curriculum focused on the "Native Transfer" functionality as the simplest building block of a Casper platform.

**Comment by ramujin** [comment]
@ShalmaliCL identified these links for potential Module 1 content.

[Creating Account and Keys](https://docs.casper.network/concepts/accounts-and-keys/#creating-accounts-and-keys)
[Funding the Testnet Account](https://docs.casper.network/users/testnet-faucet/)
[Native transfer](https://docs.casper.network/resources/tutorials/advanced/list-cspr/#native-transfer)
[Direct Token Transfer](https://docs.casper.network/developers/cli/transfers/direct-token-transfer/)
[Token Transfer using Block Explorer](https://docs.casper.network/users/token-transfer/)

We can use them as a starting point for this card.

**Comment by ShalmaliCL** [comment]
@ramujin - Please find the first draft of the module 1 structure [here.](https://casperlabs.atlassian.net/l/cp/Qj1PBjTu) Request your review and advise

**Comment by ramujin** [comment]
@ShalmaliCL the draft looks pretty good. I made a few comments on it, particularly about the order of things. Let me know what you think.

**Comment by ShalmaliCL** [comment]
@ramujin @ipopescu  - Thank you for your suggestions!
I have incorporated them as well, let me know what you think.
@ACStoneCL - Request you to please review and advise.

**Comment by ramujin** [comment]
I just did another pass @ShalmaliCL. I only left 1 more comment and then we can see what @ACStoneCL thinks before we pass it up to Karan for review.

**Comment by ACStoneCL** [comment]
I like this, I think it will make a great introduction to both Casper and the Native Transfer functionality.

**Comment by ipopescu** [comment]
I left a couple of comments on the confluence page.

**Comment by ShalmaliCL** [comment]
@ipopescu - Thank you for your suggestions! I have addressed your comments.
