### ISSUE TITLE
Content Creation for Casper Curriculum Module 1

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1142]
This ticket accounts for work towards completing the content for Casper Curriculum Module 1, based on the discovery done in ticket #1122.

**Comment by ShalmaliCL** [comment]
The content of module 1 is [here.](https://casperlabs.atlassian.net/l/cp/x3GhXw0m)
Module 1 has 5 subtopics. Each subtopic now has a confluence page with the expected content.
The remaining work and team review will be completed as a part of #1155 
CC: @ACStoneCL
