### ISSUE TITLE
Finalize and Review Content for Casper Curriculum Module 1

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1155]
This ticket follows up on the work done with [Content Creation for Casper Curriculum Module 1 #1142](https://github.com/casper-network/docs/issues/1142) to account for the real-time review necessary for [Casper Curriculum Module 1](https://casperlabs.atlassian.net/wiki/spaces/DEVEXP/pages/1901789185/Module+1).

**Comment by ShalmaliCL** [comment]
[Module 1](https://casperlabs.atlassian.net/l/cp/8K14iqoh) content is in review.
Reviewer: @ramujin @ACStoneCL

**Comment by ramujin** [comment]
@ShalmaliCL I went through all sections and made revisions. I think Sections 5 and 6 still need work. For Section 5, we're putting too many prerequisite expectations on the developers when this is supposed to be their foremost experience with the platform. Section 6 seems rather useless to be honest... the use cases are good for marketing, but they aren't actually showing a developer why they should choose the blockchain for their development needs. @ACStoneCL any feedback from your end?

**Comment by ShalmaliCL** [comment]
Hi @ACStoneCL,
As per our last discussion, we have done the changes in[ Module 1.](https://casperlabs.atlassian.net/l/cp/Usg1f5gU) Request you to please review and advise. Thank you!
