### ISSUE TITLE
Additional multi-sig examples

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#1171]
Add additional documentation explaining the multi-sig functionality.
Reference request and repository: ~https://github.com/casper-ecosystem/two-party-multi-sig/issues/4~ https://github.com/cryofracture/multi-sig

**Comment by ipopescu** [comment]
PR submitted here: https://github.com/cryofracture/multi-sig/pull/1. The follow-up card is #1173.

**Comment by cryofracture** [comment]
README PR has been merged. Integration tests are working but am planning to meet with @gRoussac early next week to flesh out tests and ensure all scenarios are covered.
