### ISSUE TITLE
Include Multisig Example in the Docs 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#1173]
Using the example @cryofracture (Taylor) provided for a client, add to the examples in docs.

- Review the code and update the tests in this repo: https://github.com/cryofracture/multi-sig (@gRoussac)
- Overall review of changes (@cryofracture)
- Move repository content to the examples for documentation: https://github.com/casper-ecosystem/tutorials-example-wasm (@cryofracture or @gRoussac)
- Move the readme to the documentation, test the flow, add useful examples from [this old doc](https://github.com/casper-network/docs-archive/tree/master/dapp-dev-guide/tutorials/multi-sig), and link to the public repo. Branch started [here](https://github.com/casper-network/docs/tree/1171_multi_sig) (@ipopescu)

**Comment by ipopescu** [comment]
Adding @gRoussac and @cryofracture on this card. Please check the estimate. It seems good to me, split among all the tasks listed.

**Comment by ipopescu** [comment]
[The documentation](https://github.com/casper-network/docs/tree/1171_multi_sig/source/docs/casper/resources/tutorials/advanced/multi-sig) is ready for review, but I will wait to raise a PR until the code repository is ready. The docs have additional context and examples compared to the README in the code repository.

- [Multi-Sig Workflow PDF.pdf](https://github.com/casper-network/docs/files/11980843/Multi-Sig.Workflow.PDF.pdf)
- [Additional Examples PDF.pdf](https://github.com/casper-network/docs/files/11980842/Additional.Examples.PDF.pdf)

<img width="1581" alt="Screenshot 2023-07-07 at 12 25 09" src="https://github.com/casper-network/docs/assets/4185994/d4a61b04-ef0e-4da2-b238-a5785d16f5d6">
<img width="1570" alt="Screenshot 2023-07-07 at 12 25 25" src="https://github.com/casper-network/docs/assets/4185994/fc7765c2-a0e6-4209-b273-a0258c45f09b">

**Comment by ipopescu** [comment]
I need to put this back in the backlog for now...

**Comment by ipopescu** [comment]
I have reviewed the PR and updated the Readme and the tests. I am updating this [branch](https://github.com/casper-network/docs/tree/1171_multi_sig) now.
