### ISSUE TITLE
"Edit this page" is broken - wrong branch?

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/docs#1190]
The link on the bottom of each page seems to point to an non-existing branch:
https://github.com/casper-network/docs/tree/main/source/docs/casper/developers/json-rpc/json-rpc-pos.md

That one is working but I'm not sure which one is the correct branch to be used:
https://github.com/casper-network/docs/tree/dev/source/docs/casper/developers/json-rpc/json-rpc-pos.md

I guess this is a general issue in the footer/a component and not specific to that page - it is just an example.

**Comment by andrzej-casper** [comment]
Duplicate of #815.
