### ISSUE TITLE
Useless breadcrumbs and ghost home page

### ISSUE THREAD

**Issue by andrzej-casper** [casper-network/docs#1205]
We have breadcrumbs enabled, but there is no way to use them to navigate - parent categories are **not** links:

![image](https://github.com/casper-network/docs/assets/121791569/e4cf1631-293a-46da-a56d-007e17aac7ca)

I investigated this problem and it appears that sidebar is configured incorrectly: parent categories have no link associated. This should be fixed soon with https://github.com/casper-network/docs/issues/1202.

---

Breadcrumbs contain icon linked to the home page:

![image](https://github.com/casper-network/docs/assets/121791569/d01ea000-5bf0-4d91-8f73-97bb6294f25e)

What is interesting, this is the only way to navigate there (while being in docs)! This is unexpected/inconsistent behavior, as Casper logo in header is taking user to DevPortal. As discussed with @ipopescu it would better to get rid of this "ghost" home page:

- move "_What is Casper?_" section to concepts/overview
- make concepts/overview the new home page - probably with `slug: /`

**Comment by ipopescu** [comment]
Thanks @andrzej-casper. I agree with removing the ghost home page and moving the content to `concepts/overview` as part of this ticket. This page is unreachable unless someone marked the URL. The breadcrumbs should be fixed with #1202.
FYI @ACStoneCL

**Comment by ipopescu** [comment]
Hi @andrzej-casper, I've consolidated the content from the ghost page (`/`) with the content on the `concepts/index page` in this branch: https://github.com/casper-network/docs/tree/1205_ghost_page. 
However, I cannot redirect the ghost page to the `concepts/index` page. I've tried several things ([link 1](https://luctst.github.io/docusaurus-starter-pack/docs/homepage.html), [link 2](https://stackoverflow.com/questions/58665817/redirect-to-docs-from-landing-page-in-docusaurus-v2)), but I don't have enough experience to redirect successfully. Could you please take a look? cc @ACStoneCL

**Comment by ipopescu** [comment]
Thank you, @andrzej-casper. This is great! I was getting the issue when adding the slug '/' on the concepts/index.md page. But, adding it in the concepts/about.md page as you did fixes the issue. Thanks!
