### ISSUE TITLE
Complex Contract Development and Best Practices

### ISSUE THREAD

**Issue by KMCreatesWorlds** [casper-network/docs#1210]

**Comment by andrzej-casper** [comment]
Issue migrated from `docs-new` repository. **Note:** previously it had label *create*.

**Comment by ipopescu** [comment]
Best practices are already documented [here](https://docs.casper.network/developers/writing-onchain-code/best-practices/), and contract development is documented [here](https://docs.casper.network/writing-contracts/); so, I am closing this card. If additional documentation is needed, please provide a specific description as part of a new issue.
