### ISSUE TITLE
Injecting Rust Documentation References into our Docs

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1238]
From Medha:

"Folks, I got feedback from Alizee that devs are needing to learn about the Rust documentation. I think in the docs, we need more links to our docs in [crates.io](http://crates.io/).  We should assume that folks are unaware of the rust ecosystem.  We should include a list of the important crates, in the 'Getting started with Rust' - with links to them and what they do.  Then as folks go deeper (writing contracts & testing contracts) we should also highlight and include links to our rust docs."

This ticket accounts for evaluating our current documentation and injecting links to crates.io as appropriate.

**Comment by ipopescu** [comment]
Here are some links that could serve as a starting point, from the [casper-node wiki](https://github.com/casper-network/casper-node/wiki/Important-Links-for-Developers):

Essential API documentation 
https://docs.rs/casper-node/latest/casper_node
https://docs.rs/casper-types/latest/casper_types
https://docs.rs/casper-client/latest/casper_client
https://docs.rs/casper-contract/latest/casper_contract
https://www.npmjs.com/package/casper-contract
https://www.npmjs.com/package/casper-js-sdk
Essential Casper crates 
[https://crates.io/crates/cargo-casper ](https://crates.io/crates/cargo-casper%E2%80%A8)
[https://crates.io/crates/casper-client ](https://crates.io/crates/casper-client%E2%80%A8)
[https://crates.io/crates/casper-contract  ](https://crates.io/crates/casper-contract%C2%A0%E2%80%A8)
[https://crates.io/crates/casper-types  ](https://crates.io/crates/casper-types%C2%A0%E2%80%A8)
https://crates.io/crates/casper-node
