### ISSUE TITLE
[Time Box] Casper L2 ecosystem use case examples

### ISSUE THREAD

**Issue by lhg9865** [casper-network/docs#1255]
Update the document of [Casper L2 ecosystem use case examples](https://docs.google.com/document/d/1xizMQUsBlIQELpFdBgUjvMhcJCOVbKBALxPOOMDEZbg/edit?usp=drive_link)

**Comment by lhg9865** [comment]
Hi @gskerry 

I updated the document, please have a look at it if you have time, thanks
https://docs.google.com/document/d/1xizMQUsBlIQELpFdBgUjvMhcJCOVbKBALxPOOMDEZbg/edit?usp=drive_link

**Comment by gskerry** [comment]
Hey @lhg9865 
Looks like this ended up in Docs repo. Going to close out and recreate in SA.
