### ISSUE TITLE
Include Ledger in Staking Guide

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#127]
Update the [Staking Guide](https://casper.network/docs/workflow/staking#6-delegating-tokens) we have to also mention the [Ledger setup](https://casper.network/docs/workflow/ledger-setup) and that Ledger can be connected to CSPR.live to delegate tokens. 
Make sure to clarify how to use the Ledger device and [CSPR.live](https://cspr.live/) to [delegate tokens](https://cspr.live/delegate-stake). Each validator has a "Delegate Stake" button on CSPR.live.

More context [here](https://casperlabs-team.slack.com/archives/CF9JMFHAB/p1638405967169000). 

Basic document started here: https://docs.google.com/document/d/1XCzN4VKFoAhyjZaSFvViSyJY3YWiyLJZJ30nubfQk7s/edit
Please let Joe Benso know, once the document is ready. Thank you!

**Comment by ipopescu** [comment]
Re-assigning to @dylanireland.

**Comment by devendran-m** [comment]
Confirmed with @ipopescu. This is now complete, so closing it.
