### ISSUE TITLE
Initial Checkpoint Documentation

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1298]
This ticket accounts for creating framework docs around the Checkpoint system. Ideally, it would allow us to quickly update and release documentation alongside Checkpointer when it is fully ready for release.

Checkpointer Demo Video:
https://drive.google.com/file/d/1BJOyW8iZbCj71fisigd6MLE0JPWafS68/view?usp=sharing

**Comment by ipopescu** [comment]
Moving this back in "to do" in favor of updating the sidecar docs.
