### ISSUE TITLE
Full CEP-78 Use Tutorial

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1299]
Create a tutorial in a similar manner to the existing [CEP18](https://github.com/casper-ecosystem/cep18/tree/dev/docs) documentation that outlines the use of each aspect of CEP78 in a more direct and user-friendly way.

**Comment by ipopescu** [comment]
Taking on this task for the upcoming sprint.

**Comment by ipopescu** [comment]
I will merge the related PR and if Greg has additional feedback, I will open a new PR.
