### ISSUE TITLE
Blank page and incorrect right-hand navigation

### ISSUE THREAD

**Issue by GloreenS** [casper-network/docs#131]
- When you type in the address or click this link https://casper.network/docs/dapp-dev-guide you get a blank page, however, when you navigate to some other topic and return to this topic in the same window, it displays correctly. Same for Operators/Design/Glossary pages
- When you click https://casper.network/docs/workflow/setup you see the wrong right-hand navigation and the link to crates.io is a pdf file, however, if you navigate to another topic and then return to this one in the same window, it displays the topic with the correct link and right-hand navigation. Same with https://casper.network/docs/workflow

**Comment by ipopescu** [comment]
Issue assigned to sd-ditoy.
