### ISSUE TITLE
Review all references to cspr.live

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#136]
References to cspr.live need to be reviewed anywhere in the docs.
"Use a block explorer such as cspr.live".
Objective stance that CL doesn't provide cspr.live and users get confused.
We don't want to imply or state that it's our software, but a 3rd party.

Review also references to key creation. Avoid any recommendations.

**Comment by GloreenS** [comment]
Added a new topic explaining block explorers and referenced it from all the topics that use block explorers.
