### ISSUE TITLE
Incorporate Documentation Changes from PR #1366

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1369]
[Update Discord Link + Fix 6 Security Vulnerabilities. #1366](https://github.com/casper-network/docs/pull/1366) provides several beneficial documentation edits. This ticket accounts for incorporating those changes into the main branch.

**Comment by 0xE69** [comment]
Hi @ACStoneCL, I am troubleshooting the design issues. 

I will also propose an update to actions once complete for the new node version.

**Comment by 0xE69** [comment]
I have updated everything including docusaurus v3, Just requires some additional styling will push shortly.

**Comment by ipopescu** [comment]
@0xE69 are there any updates here? Looks like this work was dropped.

**Comment by ipopescu** [comment]
I closed PR 1366 due to inactivity, so I am closing this task.
