### ISSUE TITLE
Document the Zug Protocol

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1414]
This ticket accounts for work to document the Zug protocol for external consumption on the docs site.

**Comment by ipopescu** [comment]
Planned tasks:
- review all related materials, including related to rewards; take notes - done
- create an outline of the design document
- review the outline with A & B, and incorporate feedback
- create a draft of the HLD document - this could be a draft PR in the docs, feat-2.0 branch
- review the draft with A & B and other stakeholders, and incorporate their feedback
- finish the draft and submit the PR for a final review
