### ISSUE TITLE
Document the Rewards System for Zug

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#1415]
This ticket accounts for work done to document the rewards system in the Zug Protocol for Condor's release.

**Comment by ipopescu** [comment]
Planned tasks:
- [ ] review the related CEP (in progress by AL) and related presentations
- [ ] create an outline of the design document
- [ ] review the outline with A & B, and incorporate feedback
- [ ] create a draft of the HLD document - this could be a draft PR in the docs, feat-2.0 branch
- [ ] review the draft with A & B and other stakeholders, and incorporate their feedback
- [ ] finish the draft and submit the PR for a final review
