### ISSUE TITLE
Document trie-store general capabilities

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/docs#143]
Document the capabilities of a trie store. Explain different types of storage on the Casper Network.

Recommendations from Docs Refinement session on 4th May'22:
- Check it's relevance and if relevant, add a design document as part of 2.0 release

**Comment by ipopescu** [comment]
This card won't be addressed in the current sprint, so moving it back to the backlog.

**Comment by ipopescu** [comment]
Is this card still needed @devendran-m and @devendran-m https://docs.casperlabs.io/design/reading-and-writing-to-the-blockchain/?

**Comment by devendran-m** [comment]
@ipopescu In my view, this issue can possibly be converted into Architectural Infographics. May be we can get clarity from @darthsiroftardis in Docs Grooming.

**Comment by ipopescu** [comment]
Infographic completed: https://docs.casperlabs.io/design/casper-design/#global-state-trie.
