### ISSUE TITLE
Investigate reusability of content

### ISSUE THREAD

**Issue by GloreenS** [casper-network/docs#160]
Check if reusing content is possible with .md files, for example, instructions for casper-client installation are repeated in multiple topics and any change leads to updating multiple files, which shouldn't be required and can be missed out leading to inconsistency.

**Comment by ipopescu** [comment]
@GloreenS do we still need this card or should we close it for now?

**Comment by ipopescu** [comment]
Can we please close this if it's not needed @GloreenS and @devendran-m ?

**Comment by devendran-m** [comment]
@ipopescu, @GloreenS, I am closing this for now until we have enough sprint cycles to take up the analysis on this.
