### ISSUE TITLE
Create a  section about the Signer integration

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/docs#176]
including the whitelisting process for the new sites

**Comment by piotr-dziubecki** [comment]
https://github.com/casper-ecosystem/signer/issues/new?assignees=George-cl&labels=Integration&template=whitelisting_request.yml&title=%5BIntegration%5D%3A+Name+of+Your+Project

link to the form

**Comment by ipopescu** [comment]
I need help from @George-cl to complete this guide. This will probably move to next sprint, sorry about that! Thank you!

**Comment by ipopescu** [comment]
Section created on the Signer wiki: https://github.com/casper-ecosystem/signer/wiki/Signer-Developer-Guide.
Most importantly, it mentions the Whitelisting guide. The rest of the guide needs input from the dev team. 
As far as this task is concerned, I think we can consider it done.
