### ISSUE TITLE
Session vs Contract context

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#188]
Pair with a developer to document the different flavors of execution context; cover usage of running session code vs the code that is part of the contract:
- About session code: when you submit code the runs in the “main space of the account”, using the account's main keys. Session code is contract code that executes in the context of the account. Example: When a contract does something to the main keys, the code runs as session code, in the session context.
- About contract code: if the code goes into the context of the contract, it switches to run as part of the “contract context”. Calling a contract entry point is like calling into a function. You cannot call a session entry point from a contract. You always want to do it in a contract context — such as incrementing a count (in the counter tutorial).

The latest discussion is [here](https://casperlabs-team.slack.com/archives/C01U1AVERFB/p1644755252465569?thread_ts=1644542884.484359&cid=C01U1AVERFB):
Summary: there are 3 ways for wasm bytes to be executed as part of a deploy:
- session bytes passed as part of the deploy ("Session Module")
- session bytes previously stored to the chain and then reused by zero or more later deploys ("Stored Session")
- smart contract bytes previously stored to the chain and called by zero or more later deploys directly or by other executing session or contract logic ("Smart Contract")

Also, see https://github.com/casper-ecosystem/context-explanation/tree/master/context.

Some additional discussion [here](https://casperlabs-team.slack.com/archives/CENA68V7Z/p1627050873276000).

**Comment by ipopescu** [comment]
Removing the assignee so that the card remains open for prioritization and assignment to whom is available next sprint.

**Comment by devendran-m** [comment]
Merged this issue into #284 . This will now be addressed by 284. Hence closing.
