### ISSUE TITLE
CEP-47 Tutorial (Part 3) - Add Testing Framework Section 

### ISSUE THREAD

**Issue by Buddhika-Pathirathna** [casper-network/docs#200]
Part - 3 - Continuation of issue  - https://github.com/casper-network/docs/issues/58

- Describe how to listen to events using events listener (built in JS-SDK) and parsing them using `CEP47EventsParser`
- Describe and include the code samples for CEP-47 tutorial's Testing Framework section.

**Comment by ipopescu** [comment]
@devendran-m @Buddhika-Pathirathna we should close this card because we are now focusing on CEP-78. If we need a tutorial for CEP-78, please open a card, @devendran-m.
