### ISSUE TITLE
Add a dev FAQ structure to docs-app

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#214]
Create a section in the documentation for an FAQ for developers. 
1. Select the page where the FAQ should live
2. Add the topics you have seen during onboarding
3. Work with Iulia to add some of the topics below, which are older and have been noted in this card.
Thank you!

**Questions collected previously**

**Does the node API have a 'getTransactions' function ?**

The node API JSON-RPC endpoints are as follows:
- "account_put_deploy"
- "info_get_deploy"
- "info_get_peers"
- "info_get_status"
- "chain_get_block"
- "chain_get_block_transfers"
- "chain_get_state_root_hash"
- "state_get_item"
- "state_get_balance"
- "chain_get_era_info_by_switch_block"
- "state_get_auction_info"

The node API SSE events are as follows: 

- BlockAdded
- DeployProcessed
- ConsensusFinalitySignature

Via. a combination of the above you can pull information from the chain such as transaction sets.

**How would be query transaction for an account?**

On chain accounts are associated with an account address.  Transaction data includes account address as a sub-field.

**Is there a service like infura.io that we can use now or in the future?** 

Not atm but https://make.services are actively building out such a service.  Contact Michael Steur for further information.

**To scale queries for thousands of clients, we would need to run multiple nodes or index the blockchain ourselves.**

Perhaps collaborating with make.services might fulfill your requirements and contribute to the wider eco-system at the same time.

**For wallet generation, can you point me to an open-source implementation or library? I see CasperLabs uses the ed25519 curve. Can you give me more specifics for seed generation?**

The only wallet like application atm is the Casper Signer - a google chrome extension.  But it is simplistic & has not been security reviewed.   The CSPR chain supports ed25519 as well as secp256k1, therefore extending a current wallet implementation would not be difficult.  CSPR will be registered on slip-0044 and the recommended seed derivation path documented.

**Comment by Buddhika-Pathirathna** [comment]
In Progress. Setting up Docusaurus

**Comment by ipopescu** [comment]
If Michael is done with the Docusaurus updates, we can move this only to the new docs (docs-app). Otherwise, we have to also add it in the old docs.

**Comment by ipopescu** [comment]
Work submitted for review and now addressing review comments.

**Comment by Buddhika-Pathirathna** [comment]
Attending review feedback and further changes.
