### ISSUE TITLE
1 pager on "listing CSPR" that outlines all the things that are needed 

### ISSUE THREAD

**Issue by cspramit** [casper-network/docs#222]
1 pager on "listing CSPR" that outlines all the things that are needed like:
Keygen
transfers
Blocks & finality signatures

Plan of action:
- Step 1 - Info gathering
- Step 2 - If info is not available, create a document with instructions covering details like deploys, json rpc etc...

**Comment by ipopescu** [comment]
@GloreenS this might be a duplicate?
