### ISSUE TITLE
Align on SDK requirements

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/docs#230]
Aim - ACStoneCL and @darthsiroftardis align on SDK requirements. Main discovery task.

Discovery Approach 
- Parse JSON RPC self-documentation
- Determine “Fundamental” versus “Informational” requirements
- Identify serialization standard updates/references required in detailing/documentation

**Comment by ACStoneCL** [comment]
Revising estimate to better reflect reality.

**Comment by ACStoneCL** [comment]
Alignment complete / work on document well underway.
