### ISSUE TITLE
ERC-20 tutorial removal from docs and corrections

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#245]
ERC-20 tutorial needs updates. This is the feedback received from Make regarding the tutorial on ERC-20 found here https://casper.network/docs/erc20.

- Change the name of the wasm to point to the correct file, which should be https://github.com/casper-ecosystem/erc20/blob/master/example/erc20-token/src/main.rs. This file has all the required functions. The current file in the tutorial does not have all the functions implemented.
- Update the instructions to point to the correct file above and mention the required arguments in the sample command. - For example, update the [deploying contract command] (https://casper.network/docs/dapp-dev-guide/tutorials/erc20/deploy#deploying-the-contract-1):
> casper-client put-deploy --node-address http://195.201.174.222:7777 --chain-name casper-test --secret-key "/home/kara/Downloads/erc20_keys/secret_key.pem" --payment-amount 100000000000 --session-path "/home/kara/code/erc20/target/wasm32-unknown-unknown/release/erc20_token.wasm" --session-arg="symbol:string='ETT'" --session-arg="total_supply:u256='50000000000'" --session-arg "decimals:u8='9'" --session-arg "name:string='ERC20 Test Token'"
- The payment amount is too little and needs to be increased to at least 50 CSPR for deployment to TESTNET

**Update as on 03/16:** Also, remove the tutorial refs from casper.network/docs and move it to https://github.com/casper-ecosystem/erc20 repo

**Comment by ipopescu** [comment]
@Buddhika-Pathirathna @devendran-m I am re-opening this card because the tutorial was never removed from the main documentation. Please remove it and then close this card.
See https://docs.casperlabs.io/erc20/.

**Comment by Buddhika-Pathirathna** [comment]
PR- [346](https://github.com/casper-network/docs/pull/346) was created to remove this folder.
