### ISSUE TITLE
Document list_authorization_keys in FFI 

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#246]
Create a simple how-to that demonstrates how to use `runtime::list_authorization_keys`.

@gRoussac has already provided the code here: https://github.com/casper-ecosystem/authorization-keys-example/pull/1.

---

After this task, we need to create another ticket for a future sprint that also demonstrates how to:
- get caller
- get immediate caller

Context: we discussed the equivalent of _ecrecover_ - a method on the FFI to load keys that sign a deploy. We mentioned that we need to document the general security model, which is already covered in the design section.
Casper provides associated keys of the signatures, and it's different than reverify-ing the signatures with _ecrecover_ that uses elliptic curve cryptography.

**Comment by ipopescu** [comment]
@RitaMAllenCA, we met today and discussed this card. I need @gRoussac's help with the code & content for this, so we increased the estimate to 13 points. It may finish after the assigned sprint.
Also, I updated the description to clarify the requirements, and we will need an additional card to document the "get_caller" and "get_immediate_caller" functions.

**Comment by gRoussac** [comment]
Hi both, as discusses I am opening a first PR for auhtorization keys how to 

https://github.com/casper-ecosystem/authorization-keys-example/pull/1

cheers

**Comment by ipopescu** [comment]
The content Greg provided is great so far. I am still working on this task, which will roll into the next sprint.
The partial content is in [this branch](https://github.com/casper-ecosystem/authorization-keys-example/tree/add_a_tutorial) to track what I have so far. I'll need a review and a brief discussion in the second half of the next sprint.

**Comment by ipopescu** [comment]
@gRoussac, the documentation is ready for review and discussion when you have time: https://github.com/casper-ecosystem/authorization-keys-example/pull/3. This card is marked for the next sprint, but tagging you just in case you have time earlier (no rush).

**Comment by ipopescu** [comment]
The remaining work for this card is only a couple of points, depending on review feedback from @darthsiroftardis and @gRoussac.

**Comment by gRoussac** [comment]
@ipopescu @RitaMAllenCA I am okay with the main PR and the doc PR. Please make it review by @darthsiroftardis so that we can merge on dev. Even if there are things to change, we can raise new PR's against dev after this merge. Thank you

**Comment by ipopescu** [comment]
Let's merge and continue to review. What's left to close the ticket:
- a review from @darthsiroftardis 
- publishing the tutorial and getting a review from @ACStoneCL

**Comment by ipopescu** [comment]
Moving back in progress to move files to the new location.

**Comment by ipopescu** [comment]
Moving this back in progress until I can open the final PR for this task. First, I need to update the feat-1.5.0 branch.

**Comment by ipopescu** [comment]
Task #1004 will add the corresponding links (marked as TODO's in the comments) once this repository goes public: https://github.com/casper-ecosystem/tutorials-example-wasm.
