### ISSUE TITLE
Add a banner to our Casper repositories

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#249]
Add a banner to all casper-network repositories. Work with Travis to get the logo. Here are some examples:
- https://github.com/paritytech/wasmi
- https://github.com/wasmerio/wasmer

The request came from @piotr-dziubecki, please reach out if you have questions.

**Comment by ipopescu** [comment]
@devendran-m please triage or close

**Comment by ACStoneCL** [comment]
Branding has been updated where appropriate in various repos.
