### ISSUE TITLE
Listing CSPR (Part2)

### ISSUE THREAD

**Issue by GloreenS** [casper-network/docs#259]
Two parts;
1. 1 pager doc - covered by #222
2. Adding the endpoints to  https://casper.network/docs/dapp-dev-guide/list-cspr - addressed by this card. Note - Link to this https://docs.casperlabs.io/dapp-dev-guide/monitoring-events/ page and explain the info required for Exchanges can consume.

Add information on `event` endpoints.

Ask (in bold) - Add a page for listing the endpoints and link it at the end of the page https://casper.network/docs/dapp-dev-guide/list-cspr
 "The default configuration of the Casper node provides these streams on port 9999 **at : /events (need the other endpoints)**"
Source LInk - https://docs.google.com/document/d/1k9KW67nd78oRFsMtG5fd_HUP0asmE8cjM1A6eLID6bI/edit

> Original ask (via Slack) - which is listed in #222.
> "we also need a 1 pager on "listing CSPR" that outlines all the things that are needed like:
> Keygen
> transfers
> Blocks & finality signatures"
> 

Output - https://casper.network/docs/dapp-dev-guide/list-cspr in https://casper.network/docs/dapp-dev-guide/list-cspr#the-casper-protocol section.

**Comment by devendran-m** [comment]
"Adding the endpoints" information is covered already #456.
Creating a one-pager work in progress and covered by #222.
