### ISSUE TITLE
Testnet faucet clarification

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#260]
Clarify that you can request tokens only once from a faucet; if you need more tokens, you have to create a new account. 

![Screen Shot 2022-03-02 at 23.17.37.png](https://images.zenhubusercontent.com/60785891648deb2076a7ddc1/adf76aef-263d-4b3b-8a23-eebf734d22af)

**Comment by ipopescu** [comment]
The content seems to have been removed, so I am re-opening the card.

**Comment by ipopescu** [comment]
@Buddhika-Pathirathna can you please help with this since you have the context? Either this sprint or next week. Many thanks!

**Comment by Buddhika-Pathirathna** [comment]
Sure @ipopescu , I will work on this
