### ISSUE TITLE
Misalignment in left nav bar

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#267]
Under tutorials, the titles are misaligned. Look into this.

![Screen_Shot_2022-03-04_at_9_48_12_PM.png](https://images.zenhubusercontent.com/60785891648deb2076a7ddc1/c191b9e0-0343-40fa-b374-36ff6eb59923)

**Comment by ipopescu** [comment]
@sd-ditoy, is it possible to get your help with this item?

**Comment by sd-ditoy** [comment]
I've had a look and corrected/fixed the styling for sublists. You can preview these changes on the specific branch for this issue (https://github.com/casper-network/docs/tree/267-misalignment-in-left-nav-bar).
