### ISSUE TITLE
casper-node developer docs

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#273]
As a developer, I want to find documentation covering design decisions and how something works in a bigger context, so it needs to live outside of the code comments. Code comments are useful when I zoom in, but sometimes I need a bigger/historical picture. Also, I want these docs to be closer to the code so that I can search them easily and contribute to them as I work on the code.

Proposal: we could have docs in markdown, actually inside the node repo (in a _docs_ or _design_ folder) and they could be linked to from the top-level README. These docs are purely related to the code.

**Acceptance criteria**:
1. Come up with the desired structure and add it in the casper-node repository
2. Add a first article
3. Update the top-level README if needed

**Comment by marc-casperlabs** [comment]
This has been rejected in its current form, this will need follow-up work to instead integrate this into the rustdoc.
