### ISSUE TITLE
Update "Understanding Hash Types" in docs

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#278]
Update "Understanding Hash Types" in docs. It needs updating with new Key variants added recently

Via Ticket Request;

(https://casperassociation.slack.com/archives/C02FE1UTRS6/p1647346564741409)
:ticket: Update "Understanding Hash Types" in docs
This is a doc ticket.  It needs updated with new Key variants added recently

**Comment by ipopescu** [comment]
Closing as done.
