### ISSUE TITLE
Remove references/mentions of  ERC20 & CEP47 from casper.network/docs

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#281]
- [ ] Remove ERC20 and CEP47 Tutorials & any associated references from casper.network/docs
- [ ] Move the tutorials to casper-ecosystem/erc20 and cep47 repos
- [ ] If needed, add a link to repos in casper.network/docs for any usable reference implementations

**Comment by ipopescu** [comment]
@devendran-m @Buddhika-Pathirathna, could Buddhika take this ticket this sprint?

**Comment by Buddhika-Pathirathna** [comment]
> @devendran-m @Buddhika-Pathirathna, could Buddhika take this ticket this sprint?

Hi @ipopescu, I will take this to this sprint.

**Comment by devendran-m** [comment]
Related PR #388
