### ISSUE TITLE
Smart Contract Authoring

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#282]
Step 1 -  
Why do you need it
how to build it
Fundamentals
Document Session Code's Importance

Step 2
Install reusable code on-chain, basic smart contract

Step 3
More advanced secured smart contract, ability to pay, receive payment

Step 4 
Multi contract arrangement/wrapper

Step 5
Upgradable feature, when to use, when not to use, when to lock, why to lock (e.g. for security purposes) etc

**Comment by ACStoneCL** [comment]
Closing as complete.
