### ISSUE TITLE
Smart Contract Developer Documentation

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#283]
This is an Epic that will aim to create documentation that will provide essential information and reference required for users to successfully develop smart contracts on Casper Network. Details below;

**Intro about Urefs, Purses, Types, Global States**
- [x] #109 
- [x] #286 
**Note:** Moved (#187) to dApp Epic. Subset of this that is relevant to Smart Contract Dev will be updated in Smart Contract Documentation_

**Session Code**
- [x] #188 
- [x] #284
- [x] #329 
- [x] #330 
- [x] #331 

**How to Write, Maintain and Upgrade Smart Contracts**
- [x] #285 
- [x] #289 
- [x] #217
- [x] #307 
- [x] #91 
- [x] #349 
- [x] #393 

**Best Practices**
- [x] #82 
- [x] #298 
 
**Others**
- [x] #361 
- [x] #96 
- [x] https://github.com/casper-network/docs/issues/514

**Comment by ipopescu** [comment]
@devendran-m having examples for each of these topics would be useful. Can we add examples to the acceptance criteria?

**Comment by devendran-m** [comment]
As per Docs Grooming on 4th May, moved #187 to dApp epic and once done, take the subset of Smart Contract Development relevant info and include it in the Smart Contract Developer Documentation section.
