### ISSUE TITLE
Update the Glossary 

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#283]
Define the following terminology when first introduced in the Casper docs: https://docs.casperlabs.io/en/latest/.
Then add the explanations in the glossary section here: https://docs.casperlabs.io/en/latest/glossary/index.html
We might already have some of the terms, please check.
 
	1.	Turing-complete blockchain: what is turning completeness? how does it apply to blockchain?
	2.	Smart contract platform : what is a smart contract? what is a platform for smart contracts?
	3.	Transactions / Deploys : why do we use these terms?
	4.	Proof of Stake (PoS) : what is it? 
	5.	Consensus: what is consensus in blockchain? Point to Highway in the glossary. 
	6.	WebAssembly (uncommon for most web developers) 
	7.	Permissionless : what does it mean for a network to be permissionless? Why is it important?
	8.	Correct-by-construction : what does it mean? Why is it important?
	9.	Provably safe and live under partial synchrony : what does it mean? Why is it important?

**Comment by CryproAde** [comment]
We have the following terminologies in the glossary section already: POS, WebAssembly, Consensus, CBC (needs to be expanded and explained in detail - the existing definition is just a one-line sentence).

**Comment by ipopescu** [comment]
@CryproAde I think you can focus on CBC and the ones that don't exist yet. The rest are probably ok for a definition.

**Comment by CryproAde** [comment]
Ok, got it @ipopescu.

Then as for the definition of smart contract in the glossary section, we need to define what a smart contract is then introduce WASM. The current explanation doesn't define what a smart contract is

**Comment by ipopescu** [comment]
Moving this card to next week, so we can add the content to the new documentation portal based on Docusaurus.

**Comment by ipopescu** [comment]
https://docs.google.com/document/d/14-qhdCNF8FL6FtmOxLV_vJVUjb8vNuLZ6Zo6oA3pZEY/edit#

**Comment by ipopescu** [comment]
Completed.
