### ISSUE TITLE
Document how to maintain and upgrade contracts

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#289]
User Story - As a smart contract developer I would like to understand how to maintain ~and upgrade~ contracts by going through the relevant documentation in docs.casperlabs.io website

- ~how to maintain the contracts~
- how to upgrade the contracts

Related card #279 

**Please note that there is #179 is available for upgrading contracts documentation. Review #179 and if caters to the above user story objective close this user story/issue and either refine 179 or upgrade 179 as required.** 

Acceptance criteria - Documentation that can successfully guide a smart contract developer to successfully maintain ~and upgrade~ their contract

**Comment by Buddhika-Pathirathna** [comment]
The 'how to maintain the contracts' part also is covered by the Linked card https://github.com/casper-network/docs/issues/279 (https://github.com/casper-network/docs/issues/179 ). Hence, closing this card.

**Comment by ipopescu** [comment]
@Buddhika-Pathirathna @darthsiroftardis we need to re-open this card. The "maintenance" piece is not covered in #279, which is a very specific edit. 
Please guide developers regarding the maintenance of their contracts. For example, do they need to update their contract / session code when a new version of the node is released? Do they need to update any types? Do they need to update any versions?
Upgrades are a separate topic.
