### ISSUE TITLE
Written tutorial for the Signer

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#291]
Create a written tutorial for the Signer. Most of the steps are already covered in the Staking guide: https://casper.network/network/blog/how-to-stake-your-cspr.

However, we need a tutorial dedicated only to the Signer. Many community members have requested such an article. Also, there are additional features there were not covered in the Staking guide.

Note that the UI is changing, so try to keep the screenshots to the minimum number required. Focus more on the flow and on the navigation.

We also have community guides here: https://docs.cspr.community/. Please review them and take out what is useful, especially the [Signer Guide](https://docs.cspr.community/docs/user-guides/SignerGuide.html) and [Connect a Wallet](https://docs.cspr.community/docs/user-guides/Connect-a-Wallet.html).

When the article is ready, add it to the new documentation hosted on Docusaurus.

**Comment by CryproAde** [comment]
Here is the created document:
https://docs.google.com/document/d/1pkzY93HjcZqcujJwxia6dY3txJwtcIcAwxYfaNkiTVw/edit?usp=sharing

**Comment by ipopescu** [comment]
This is done, thank you @CryproAde. We will move it later to the docusaurus portal.

**Comment by GloreenS** [comment]
Worked Sunday to close this task within this sprint. Link to document in progress https://docs.google.com/document/d/1T5bO0nWPtOh4CMcYWg-diOoGujIwNmRXyt96qDq1nos/edit?usp=sharing

**Comment by GloreenS** [comment]
@ipopescu Draft for Signer is complete [here](https://docs.google.com/document/d/1T5bO0nWPtOh4CMcYWg-diOoGujIwNmRXyt96qDq1nos/edit?usp=sharing) moving to review.

**Comment by ipopescu** [comment]
Thank you, @GloreenS. I left some minor suggestions in the document. Is there time to also add the guide to the documentation? If not, let's create another card for next sprint, for adding the guide in the external documentation ([here](https://docs.casperlabs.io/en/latest/dapp-dev-guide/index.html) and [here](https://casper.network/docs)).

**Comment by ipopescu** [comment]
We'll open a new card for adding it to the external docs.
