### ISSUE TITLE
Refresh AssemblyScript page?

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#302]
Does this page needs a refresh?
https://casper.network/docs/dapp-dev-guide/writing-contracts/assembly-script/

We need to run this by the team in grooming @devendran-m. Thank you!

**Comment by RitaMAllenCA** [comment]
@ACStoneCL @ipopescu This is OLD, is it still relevant?  Does it need to be updated for 1.5?  or in the new structure?

**Comment by ACStoneCL** [comment]
@RitaMAllenCA I don't think it's a bad idea to update it - we'll just need to identify who can actually provide SME input for it.

**Comment by ipopescu** [comment]
@RitaMAllenCA I agree with @ACStoneCL. Even if it's an old ticket, it is still valuable to update this page, but we need a dev to look at it.

**Comment by ACStoneCL** [comment]
Closing for a refreshed and repurposed ticket.
