### ISSUE TITLE
Include a header in the Ledger setup

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#310]
Currently, the header is available in experimental mode. This entry is created to include a header in the Ledger setup until fully released by Ledger

Reference repo - https://casper.network/docs/workflow/ledger-setup
Reported by - @sacherjj

**Comment by devendran-m** [comment]
Since the Ledger release went in April, this card is no longer is required.
@sacherjj , could you confirm if this can be closed please?

**Comment by ipopescu** [comment]
The Ledger is live and we don't need to add a note that it's in experimental mode.
