### ISSUE TITLE
Casper CLI Client - Alternative install instructions for Ubuntu 18.04/20.04

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#311]
Objective - 
- To include alternative install for client, for Ubuntu 18.04/20/04 instructions to repo.casperlabs.io and include `sudo apt install capser-client`
- Also add rpm and possibly other client platforms, so that there are options 
- The cargo install only works if Rust is already installed. This information should be called out in the documentation

Reported by @sacherjj 
Reference (original request/reported content)

> https://casper.network/docs/workflow/setup
> Casper Command-line Client
> We should include alternative install for client for Ubuntu 18.04/20.04 with adding [repo.casperlabs.io](http://repo.casperlabs.io/) (instructions if you load that) and sudo apt install casper-client
> Will follow installing casper-node-launcher from here https://casper.network/docs/operators/setup but only install casper-client.  We will be adding rpm and possibly other client platforms so we would have this as various options.
> This cargo install only works if Rust is already installed and should have a call out for this.

**Comment by bradjohnl** [comment]
https://github.com/casper-network/docs/pull/434
