### ISSUE TITLE
Host and display the JSON-RPC schema in an easier to read format - Mainnet

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#313]
**Request**:

- We can currently query the node: http://65.21.235.219:8888/rpc-schema.
- Or use the Casper client subcommand list-rpcs.
- MAKE created this URL for the previous version (1.0.0): http://casper-rpc-docs.s3-website-us-east-1.amazonaws.com/.
- Please help create a similar link for the Mainnet 
- Source: Fraser, Iulia

**Component**: JSON-RPC
**Assignee**: SRE team
cc: @sacherjj @bradjohnl

**Comment by ACStoneCL** [comment]
Closing this ticket and #314   based on the discussions here in and the fact that we host the JSON-RPC API in its entirety on the docs site.
