### ISSUE TITLE
Add deploy payment examples

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#324]
Add more examples for how the deploy payment can be specified. See story #84 and [PR 323](https://github.com/casper-network/docs/pull/323).

**Comment by ipopescu** [comment]
@devendran-m assigning this to you to discuss in grooming.

**Comment by ACStoneCL** [comment]
Closing this ticket as deploy payment information has expanded significantly in the time since we opened it.

See:
https://docs.casper.network/concepts/serialization-standard/#payment--session
https://docs.casper.network/developers/writing-onchain-code/calling-contracts/
