### ISSUE TITLE
Update JavaSript/TypeScript Client SDK Library as per updated SDK Spec

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#352]
We have recently updated the Casper SDK Specification. You can find the updated documentation here: https://docs.casperlabs.io/dapp-dev-guide/sdkspec/introduction/.

Please take a look at the updated Casper SDK Specification and make necessary updates/changes to the JavaScript/TypeScript Client SDK Libraries that you are maintaining.

Should you have any questions or feedback regarding the updated SDK Specification, please do not hesitate to revert on this issue.

**Comment by hoffmannjan** [comment]
Hi, I think this can be bigger topic then we expect. I would address all of the changes in v3, along with other breaking changes.

**Comment by devendran-m** [comment]
Hi @hoffmannjan , thank you for sharing your views. If you think it can be addressed in v3, then I will close this issue here and we can add a card under JS SDK repo for tracking this along with v3 updates.



> Hi, I think this can be bigger topic. I would address all of the changes in v3, along with other breaking changes.

**Comment by ipopescu** [comment]
@devendran-m please remove this from here and add it to the respective repository.

**Comment by devendran-m** [comment]
Closing this ticket as this scope of work will be addressed via https://github.com/casper-ecosystem/casper-js-sdk/issues/193
cc: @hoffmannjan

**Comment by devendran-m** [comment]
> Closing this ticket as this scope of work will be addressed via [casper-ecosystem/casper-js-sdk#193](https://github.com/casper-ecosystem/casper-js-sdk/issues/193) cc: @hoffmannjan, @ipopescu
