### ISSUE TITLE
Calling Contracts page seems wrong / off

### ISSUE THREAD

**Issue by MParlikar** [casper-network/docs#363]
https://docs.casperlabs.io/dapp-dev-guide/calling-contracts/

This page has a few problems:
1) The example adds a contract version under 'Installing a contract' which is misleading, and should be included in 'upgrading contracts'
2) The page references storing the contract under named keys -but doesn't talk about the pattern for doing this.  Also it implies that this is a requirement, which I believe it is not?  I think @darthsiroftardis needs to take a deep look at this page.

**Comment by ipopescu** [comment]
@ACStoneCL #349 was already opened for next sprint and this card seems to be a duplicate. What do you want to do in this case?

**Comment by ACStoneCL** [comment]
@ipopescu I think as long as we capture the concerns from this card, we should be good to combine it into #349

**Comment by ipopescu** [comment]
#349 already contains estimates, so I will keep this one open without an estimate to make sure I address all the concerns.
