### ISSUE TITLE
Identify outdated/harmful information in the docs for removal

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#376]
Remove outdated/harmful information from the documentation until they are replaced with the correct content.

Plan of action:
Step 1 - Do a pass of all documentation in https://docs.casperlabs.io/
Step 2 - Identify contents that are outdated and harmful
Step 3 - Create specific tickets for removing outdated/harmful info from the docs, based on the outcome from Step 2

**Comment by ACStoneCL** [comment]
Closed as complete.
