### ISSUE TITLE
Documenting role based security for smart contracts

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#382]
The objective of this issue is to create documentation explaining role-based security for smart contracts in detail, with required examples.

Reported by @dylanireland 
Target Release/Release Priority - 1.5.0

**Comment by deuszex** [comment]
@dylanireland what do you mean by the role-based model?
- We have the `groups` that is afaik going away in 2.0
- We have `deployer` account based implementations in cep47 NFT codes.

**Comment by devendran-m** [comment]
This is superseded by #443 . Therefore closing this ticket.
