### ISSUE TITLE
Understand multi-signature workflow

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#390]
Understand how to run a smart contract to create associated keys; a full example is found in the Multi-sig tutorial. 
Understand and test the multi-signature workflow found here: https://docs.casperlabs.io/en/latest/workflow/two-party-multi-sig.html

**Comment by GloreenS** [comment]
- Tested the example in [Two-party multi-sig](https://docs.casperlabs.io/en/latest/workflow/two-party-multi-sig.html) topic.
- Deployed the smart contract to create associated keys using multi-sig tutorial.
- Made a note of observations in card to updated multi-sig tutorial.
- Understood and verified the output using nctl commands.
