### ISSUE TITLE
Global changes - ensure consistency of terms across docs

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#404]
Please ensure consistent use of terms across the documentation. Following are some of the Global changes required within documentation;

- [x] Replace `Wallet` with `Account` or `Purse` as appropriate (3 points) - PR https://github.com/casper-network/docs/pull/868
- [x] Replace `commission` with `delegation rate` as appropriate (0 points)
- [x] Remove `In-memory` from all virtual machine references (0 points)
- [x] Review Account hash vs account address usage and use AccontHash as appropriate. (1 point)
- [x] Describe who each document is for - This is already addressed to an extent via https://github.com/casper-network/docs/issues/365. The remaining work will be addressed in #847

**Comment by ipopescu** [comment]
Please prioritise this @devendran-m in the next sprint if possible.

**Comment by RitaMAllenCA** [comment]
@ipopescu please estimate for sprint entry.  I do not know if we will put it in the sprint, but please estimate anyway. thank you
