### ISSUE TITLE
Rename ERC20 repo to CEP18 or Fungile Token

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#418]
Rename ERC20 repo https://github.com/casper-ecosystem/erc20 to CEP18 or Fungile Token

NOTE: In the readme, include the reference to the ERC20-like standard.

**Comment by ipopescu** [comment]
@devendran-m This is an old ticket and I don't think it should be part of this repository. Also, it may not be addressed. Please check if we can close it.

**Comment by devendran-m** [comment]
This will be addressed via the wider Products work. Reference - Issue 338 in Products
