### ISSUE TITLE
Update serialization standard to include `UnbondingPurse` and `WithdrawPurse`

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#431]
Update the serialization standard to include `UnbondingPurse` and `WithdrawPurse` . 

- Release 1.5.0 will introduce the Redelegate feature which introduces the `UnbondingPurse` and renders the historical data represented as `WithdrawPurse` as defunct
- Please note that the **SDK** and **serialization standards** both need to be updated in accordance with these changes

Note - SDK Authors have to incorporate this ahead of v1.5.0 release. @devendran-m to inform SDK Authors in SDK Fortnightly call or earlier. Share the 1.5.0 feature branch with SDK Authors when ready.

**Target Release - v1.5.0**

**Important:** Please note that this is related to 1.5.0 release. Therefore any PRs opened should target that branch - i.e. https://github.com/casper-network/docs/tree/feat-1.5.0

**Comment by darthsiroftardis** [comment]
We also need to add entries for `ChainspecRegistry` and `SystemContractRegistry`
