### ISSUE TITLE
Cleanup unused files in the Docs structure

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#436]
**Problem Statement:** There are some files and scripts which are not necessary anymore and are not used. Some of them were used by [Scal.io](http://scal.io/) but now they are useless so they can be removed.

**User Story:** As a repo maintainer, I would like to check the unused files that could include blog files, files used for testing, .circleci, crowdin files, snippets and remove the unnecessary ones from the Docs repository.   

**Definition of Done:** Functional Docs repository free from unnecessary and used files.

**Comment by ipopescu** [comment]
@devendran-m for this card, I need SRE help for sure.

**Comment by ACStoneCL** [comment]
@ipopescu Is this card still necessary after the Association restructure?

**Comment by ipopescu** [comment]
@ACStoneCL, the repo seems mostly cleaned up now. There might still be some files, such as this one, which I think we can leave for now: https://github.com/casper-network/docs/tree/dev/source/blog. I think we can close this card.
