### ISSUE TITLE
Finetune codeowners to automatically select reviewers based on context

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#440]
An intelligent default-reviewer mechanism can be set up just by experimenting with the CODEOWNERS file syntax. 
The default owner can be selected based on  file extension and path. 
It would make sense to select tech writers as reviewers for .md files, SRE/DevOps for files related to CI (./github/*) and developers for the rest.
This ticket should cover for implementing such a mechanism using the CODEOWNERS file.

**Comment by ipopescu** [comment]
@devendran-m We have so many other things to work on, please close this card.

**Comment by devendran-m** [comment]
> @devendran-m We have so many other things to work on, please close this card.

Closing as per above
cc: @ipopescu, @bradjohnl
