### ISSUE TITLE
Events Documentation - for dApp developers

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#455]
Epic to create Events related documentation that will help dApp developers in their development.

Following user stories/tickets will be tracked via this epic;

Priority items - Detailed documentation on:
- [x] #456
- [x] #457
   - State transitions within a contract including transformations of named keys
   - Event stream data source, data structure & the frequency
   - Data made available by system and how a dApp developer can use in development
   - How to parse the data & inject it into a relational database, with example parser
- [x] #458
- [x] #459

Future plans:

- [x] #460
- [x] #461

**Comment by ipopescu** [comment]
Closing the epic.
