### ISSUE TITLE
Video tutorial explaining SSE sidecar and how to use it

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#459]
Create a video tutorial explaining how to use the following ~in a dApp~, with examples where possible;
- Events
- Lifecycle
- How to use event stream info 

Deliverables:
- prepare a script and slides to demonstrate the commands (2-3 points)
- record (1-2 points)
- edit with iMovie and upload on Google drive (2 points)
- write descriptions, tags, and let the Association know that it's ready for the next step

**Comment by devendran-m** [comment]
Thanks, @ipopescu, [Document Event details, streams and life-cycle of a deploy](https://github.com/casper-network/docs/issues/456)  and [Detailed Events documentation](https://github.com/casper-network/docs/issues/457) are complete. 
[How to use event streams data for testing when building dApps]() will be prioritised next. 

You can possibly start looking at the completed stories/cards for details. In addition, please let me know if you expect Tech Writers team to create the written tutorial as well.

**Comment by ipopescu** [comment]
Thanks, @devendran-m. Sounds good. Yes, it would be great if the tech writing team creates a written tutorial. Then the dev advocates can record it.

**Comment by ipopescu** [comment]
As discussed yesterday, a dApp is not needed to demonstrate this. Once the docs are ready, I can do a short recording.

**Comment by ipopescu** [comment]
This needs to be pushed until the first version of the sidecar is released. Also, @ACStoneCL is open to taking this on; let's discuss it in the next grooming.

**Comment by ipopescu** [comment]
I reviewed the video, and it is great!

**Comment by ACStoneCL** [comment]
As the video is completed, and we have a meeting to discuss further videos tomorrow, I am going to close this ticket as the scope of "work" is done. See above link for the video in question.
