### ISSUE TITLE
Document SSE MVP for node operators

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#460]
Talk with Joe - instructions to set up and operate sidecar for Node Operators.

**Comment by ipopescu** [comment]
@RitaMAllenCA @devendran-m this card needs more information. Are the developers going to build the app?

**Comment by RitaMAllenCA** [comment]
@ACStoneCL @ipopescu Hi - I am going to align your assignments as much as possible for you to work with people in your respective time zones.  Given this, Adam will "own" the written UX for CEP-78 while Ilulia takes ownership of SSE Sidecar in the near term.  Please let me know if you have any concerns with this plan.

**Comment by ipopescu** [comment]
@sacherjj has added most of the documentation for operators in this PR: https://github.com/CasperLabs/event-sidecar/pull/50/files. 
Next, we need to finalize the configurations and clean up all the example config.toml files to be able to test and run the service.
I have reviewed the existing docs and tested the Debian package received from Joe on my node. 
The documentation that will point to GitHub is in progress here: https://github.com/casper-network/docs/tree/add_sse_sidecar.
The development has changed the existing configuration, so I am waiting on a newer config file to finish the testing and finalize this card. cc @RitaMAllenCA @George-cl

**Comment by ipopescu** [comment]
This work is done and lives in this [branch](https://github.com/casper-network/docs/tree/add_sse_sidecar). The [ETC_README.md](https://github.com/CasperLabs/event-sidecar/blob/dev/resources/ETC_README.md) contains what is needed for MVP and will go out with the .deb package. Card #805 tracks the next steps.
