### ISSUE TITLE
Explain about ports in the Config File section of Node Operator documentation

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#463]
**User Story:** As a node operator, I would like to understand by reading through the documentation;

1. the individual ports used a node operator should be aware of
2. purpose and significance of each port in a node operation
3. the ports that are open by default
4. what will happen if a port or ports are closed
5. how to leave the ports open and why it is important to leave them open
6. how to securely block them from external users/traffic

**Definition of Done:** Detailed documentation explaining the significance, usage of ports to Node Operators

**Comment by RitaMAllenCA** [comment]
more cleanup - close if not relevant
