### ISSUE TITLE
Document infra set up / server-side event stream configuration

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#464]
**User Story:** As a node operator, I would like to understand how the configuration details and set up available to me to;
- access ports securely whilst restricting access to other users/external parties
- configuration that gives an operator the choice of whether or not to leave the SSE open
- details about the ring buffer, it's depth and the no. of connections allowed

**Definition of Done:** Detailed documentation explaining the configuration options available for a node operator to secure their ports whilst allowing the intended users to access it, how to set up that configuration.

**Comment by sacherjj** [comment]
Ports are defined in the config.toml.   Default is 35000 for peer to peer, 7777 for RPC, 8888 for status and metrics, and 9999 for SSE/events.

```
# ==================================================
# Configuration options for the JSON-RPC HTTP server
# ==================================================
[rpc_server]

# Listening address for JSON-RPC HTTP server.  If the port is set to 0, a random port will be used.
#
# If the specified port cannot be bound to, a random port will be tried instead.  If binding fails,
# the JSON-RPC HTTP server will not run, but the node will be otherwise unaffected.
#
# The actual bound address will be reported via a log line if logging is enabled.
address = '0.0.0.0:7777'

# The global max rate of requests (per second) before they are limited.
# Request will be delayed to the next 1 second bucket once limited.
qps_limit = 50


# ==============================================
# Configuration options for the REST HTTP server
# ==============================================
[rest_server]

# Listening address for REST HTTP server.  If the port is set to 0, a random port will be used.
#
# If the specified port cannot be bound to, a random port will be tried instead.  If binding fails,
# the REST HTTP server will not run, but the node will be otherwise unaffected.
#
# The actual bound address will be reported via a log line if logging is enabled.
address = '0.0.0.0:8888'

# The global max rate of requests (per second) before they are limited.
# Request will be delayed to the next 1 second bucket once limited.
qps_limit = 10


# ==========================================================
# Configuration options for the SSE HTTP event stream server
# ==========================================================
[event_stream_server]

# Listening address for SSE HTTP event stream server.  If the port is set to 0, a random port will be used.
#
# If the specified port cannot be bound to, a random port will be tried instead.  If binding fails,
# the SSE HTTP event stream server will not run, but the node will be otherwise unaffected.
#
# The actual bound address will be reported via a log line if logging is enabled.
address = '0.0.0.0:9999'

# The number of event stream events to buffer.
event_stream_buffer_length = 5000

# The maximum number of subscribers across all event streams the server will permit at any one time.
max_concurrent_subscribers = 50
```

If non of these ports are opened to the external world, but punching through the firewall, they are only available on that machine.

If this occurs with 35000, the node will never peer up with other nodes as they cannot communicate back to it with port 35000.  It will get block listed for 10 min sections and never sync.  

If this occurs with 7777, 8888, and 9999, those capabilities will not be available to external ips.  There are configuration settings in the section of config.toml above that set the buffer size and subscriptions for SSE, and limits for the others.

**Comment by ipopescu** [comment]
Closing, it was addressed already. See [the docs](https://docs.casper.network/operators/setup/node-endpoints/).
