### ISSUE TITLE
Writing Session Code: test example code

### ISSUE THREAD

**Issue by ramujin** [casper-network/docs#475]
Get familiar with the example code provided in the documentation: https://docs.casperlabs.io/dapp-dev-guide/writing-contracts/session-code/.

**Comment by ramujin** [comment]
Example code is in PR 315: https://github.com/casper-network/docs/pull/315

**Comment by ramujin** [comment]
@GloreenS while trying to test the example code you provided, I run into this error, which indicates a dependence on the nightly rust toolchain.

```bash
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/ramsin/.cargo/registry/src/github.com-1ecc6299db9ec823/casper-contract-1.4.4/src/lib.rs:51:5
   |
51 |     feature(alloc_error_handler, core_intrinsics, lang_items)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/ramsin/.cargo/registry/src/github.com-1ecc6299db9ec823/casper-contract-1.4.4/src/lib.rs:51:34
   |
51 |     feature(alloc_error_handler, core_intrinsics, lang_items)
   |                                  ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `casper-contract` due to 2 previous errors
```

The instructions make no mention of needing the nightly build, so I was wondering if you ran into this issue. If the expectation is that users are running the nightly build, then we should update the instructions to explicitly say that. I know that previously we had references to nightly and they were removed in favor of using the stable toolchain, but that seems broken in this pipeline currently.

Could you please clarify this for me? Thank you!

**Comment by GloreenS** [comment]
@ramujin tagging @darthsiroftardis as he provided all the code samples and could probably answer your query better. 
@darthsiroftardis please let me know if any changes are required to the content. Thanks!

**Comment by ramujin** [comment]
I am closing this card as there is nothing more to be done until the session code docs are updated.
