### ISSUE TITLE
Analyze CI/CD link checking 

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#490]
Figure out why our link checker did not catch broken links introduced by PR #484 and fixed by PR #489.

**Comment by ipopescu** [comment]
Fyi of this new card @devendran-m.

**Comment by bradjohnl** [comment]
This has been already analyzed. See https://casperlabs-team.slack.com/archives/C0135SDEGUC/p1653578494620389

Implementation ticket has been created: 
https://github.com/casper-network/docs/issues/496
