### ISSUE TITLE
Link Boardleaf's Japanese Community site and Documentation to Casper Network 

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#495]
Broadleaf team have taken [docs.casperlabs.io](http://docs.casperlabs.io/) and translated it to Japanese. They would like to link their [Casper-Japanese community site](https://casper.blockchaintechlab.jp/) and/or [Japanese documentation on Casper](https://casper.blockchaintechlab.jp/casper-network/documentation/) with a Casper Network site.

Following a triage with @piotr-dziubecki , this ticket is created to address the above request. The plan is to create a section for development resources in local languages and link the above to that section.

**Comment by ACStoneCL** [comment]
Closed as it is no longer relevant.
