### ISSUE TITLE
How to make deploys (transfer/contract call)

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#500]

**Comment by dylanireland** [comment]
Documentation regarding transferrals, contract calls, and overall deployments has been created.

[CasperClient.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/CasperClient.ts)
[Contracts.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/Contracts.ts)
[DeployUtil.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/DeployUtil.ts)

**Comment by devendran-m** [comment]
Related PR - https://github.com/casper-ecosystem/casper-js-sdk/pull/169
