### ISSUE TITLE
Keys generation & management

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#501]
@devendran-m missing requirements

**Comment by devendran-m** [comment]
Related PR - https://github.com/casper-ecosystem/casper-js-sdk/pull/169

**Comment by RitaMAllenCA** [comment]
@hoffmannjan since this is a big PR and we are looking for Ryo to help more on the SDK, I thought that reviewing this PR would be a good task?

**Comment by hoffmannjan** [comment]
@RitaMAllenCA yeah lets assign this to him :)
