### ISSUE TITLE
Resolve Branch Conflicts in Docs Repo

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#508]
Objective of this ticket is to replace the branch  (feat-1.5.0) with the new one (feat-1.5.0_POSTREBASE) and come up with a sync mechanism on the feat-* branch as well as instruct the tech writers to use feature branches on the "feat-*" branches as well and treat them as trunks

**Comment by bradjohnl** [comment]
I have deleted the obsolete branches and renamed the "feat-1.5.0_POSTREBASE" to "feat-1.5.0". The old "feat-1.5.0" has been renamed to "feat-1.5.0_OLD" and will be deleted in a few days.

The syncing to the feature branches PR is still in review: https://github.com/casper-network/docs/pull/507

@ipopescu @ACStoneCL please approve it so I can move forward and, if everything works correctly, close this ticket.

**Comment by bradjohnl** [comment]
The sync now works.

See https://github.com/casper-network/docs/pull/520 as the first example of syncing between dev and the feature branches.

The sync is dynamic and will pick up any branch named "feat-*". The sync should still be approved manually by reviewers to make sure that we want to sync the dev changes to the feature branch at any given time.
