### ISSUE TITLE
Create Informational Endpoints Documentation

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#525]
As a developer who would like to use JavaScript/TypeScript SDK, I would like to understand the Informational endpoints offered by going through JS-based Client SDK documentation.

Definition of Done - Documentation explaining the endpoints offered, with details/examples of how to use it effectively by users in their development.

**Comment by dylanireland** [comment]
These informational endpoints have been documented

[CasperServiceByJsonRPC.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/services/CasperServiceByJsonRPC.ts)
[CasperClient.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/CasperClient.ts)
[Contracts.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/Contracts.ts)
[DeployUtil.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/DeployUtil.ts)

**Comment by devendran-m** [comment]
Related PR - https://github.com/casper-ecosystem/casper-js-sdk/pull/169
