### ISSUE TITLE
Create Transactional Endpoints Documentation

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#526]
As a developer who would like to use JavaScript/TypeScript SDK, I would like to understand the Transactional endpoints offered by going through JS-based Client SDK documentation.

Definition of Done - Documentation explaining the endpoints offered, with details/examples of how to use it effectively by users in their development.

**Comment by dylanireland** [comment]
Transfers, contract installation, entrypoint interaction documentation written [here](https://github.com/dylanireland/casper-js-sdk-docs/blob/main/TransactionalEndpoints.md).

New [DeployUtil.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/master/src/lib/DeployUtil.ts) API Reference [here](https://github.com/dylanireland/casper-js-sdk-docs/blob/main/DeployUtilAPIReference.md).

Future plans to expand within a [Signer](https://chrome.google.com/webstore/detail/casper-signer/djhndpllfiibmcdbnmaaahkhchcoijce) specific guide.

**Comment by devendran-m** [comment]
Related PR - https://github.com/casper-ecosystem/casper-js-sdk/pull/169
