### ISSUE TITLE
Create Proof of Stake Methods/Endpoints Documentation

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#527]
As a developer who would like to use JavaScript/TypeScript SDK, I would like to understand the informational endpoints offered by going through JS-based Client SDK documentation.

Definition of Done - Documentation explaining the endpoints offered, with details/examples of how to use it effectively by users in their development.

FYI @dylanireland

**Comment by ipopescu** [comment]
@devendran-m please move this to the Jira board for Dylan, as we are tracking work there and not on the L2 board.

**Comment by devendran-m** [comment]
Closing this issue as the scope of work will be tracked by the [Association Jira ticket](https://casper-association.atlassian.net/browse/DEVADV-111)

**Comment by dylanireland** [comment]
Can someone point be to the source files relevant to Proof-of-Stake Endpoints? All Contract and node communications have been documented as far as I am aware. @hoffmannjan Could you provide insight?
