### ISSUE TITLE
Documentation on creating Smart Contracts using Assembly Script

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#535]
**User Story:** As a Smart Contract Developer, I would like to read through the documentation and understand how to create, deploy and interact with Casper Blockchain using Smart Contracts written in Assembly Script.

**Objective:**  The objective of this ticket is to create/update the documentation on creating Smart Contracts using Assembly Script. 
The documentation is also expected to explain the process of developing Assembly Script-based Smart Contracts using two simple contract examples - a Hello World and a Counter contract.
- [x] #536
- [x] #537

Relevant wasm producing code can be found here - https://github.com/casper-network/casper-node/tree/dev/smart_contracts/contracts_as/example

**Definition of Done:**  Document containing clear and sufficient information, example contracts for a developer to understand the steps involved in developing Assembly Script based Smart Contract, successfully deploying it and interact with Blockchain.

**Comment by ACStoneCL** [comment]
Closed as complete - will open a ticket to verify that this info is readily available.
