### ISSUE TITLE
Fast sync documentation (learning)

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#54]
Start documenting the fast sync behavior, a major capability of the system. Engineering is updating the docs.rs documentation: https://docs.rs/casper-node/1.4.2/casper_node/.

Card 1 (next sprint)
- Understand what fast sync is, how it works, why is important. 
- Meet with the developers and review the docs.rs documentation.
- If the docs.rs section for fast sync is ready, do a review and give them feedback.
- Create cards based on your understanding for the next couple of sprints.

Ideas for the following sprints below.

Card 2 & 3
- Document the basic idea and how it works (white paper)

Card 4
- Operator-level documentation on how to interact with the fast sync feature for NEW operators

Card 5
- Operator-level documentation on how to interact with the fast sync feature for EXISTING operators
   - document the cleanup that existing operators need to do (metadata, binaries, artifacts)
   - consider what this operator needs to update or change (trusted hash, pull new binaries)
   - consider the case when a node that falls behind

Card 6
- An editorial pass to make sure the documentation is consistent, comprehensive, holistic (assign to Fraser)

**Comment by ipopescu** [comment]
Audience: CTO, lead, architect of a company evaluating our blockchain

**Comment by GloreenS** [comment]
- docs.rs documentation not available yet
- met with dev to get an initial understanding of fast-sync
- created tasks for fast-sync documentation for following sprints
