### ISSUE TITLE
Fix "Set Up Your IDE" link on the Getting Started page 

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#553]
Objective - Fix the “Set Up Your IDE” link (first link) - https://casper.network/network/developers/getting-started so that it points to https://docs.casperlabs.io/dapp-dev-guide/writing-contracts/getting-started/.

**Comment by ACStoneCL** [comment]
@devendran-m I think this might be rectified already, as the link on the casper.network page brings me to the page in question.

**Comment by Buddhika-Pathirathna** [comment]
> @devendran-m I think this might be rectified already, as the link on the casper.network page brings me to the page in question.

Yes, I also agree with that - the link redirect to the correct page

**Comment by ipopescu** [comment]
Worked with Scal.io to fix this.
