### ISSUE TITLE
Consider to create some high level graphics instead of massive text blocks only

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/docs#558]
As we all know:
Pictures speak more than 1000 words.

Checking this repo I see there is a lot going on but somehow the docs are still pretty confusing for someone who is new to Casper and new to blockchain development in general.

It lacks a high level overview of the design of the blockchain (PoS blockchain running on validators) down to each elements and the smallest entities (accounts, dictionaries, URefs, Purses) and how all of them interact with each other.

To make it easier I would suggest to add some graphics to describe some technical design fundamentals which Casper is based on.

E. g.:
- Validators running the PoS based Casper Network blockchain
- Everyone can and has to create a wallet called "account" based on either Ed... or Secp... to interact with the blockchain
- With that account the following things are possible:
   - Transfer CSPR
   - Deploy and interact with smart contracts written in Rust or another WebAssembly compatible language
   - and so on

It also lacks cross-links between topics and better navigation. For example whenever "dictionary" is used it should link to the docs for a dictionary. Same for an account, URef, Purse, Validator and so on to make it easy to look it up. Maybe even Wiki-style to show a short summary in a tooltip.

What do you think about this?

**Comment by GuybrushX** [comment]
> Thank you, @GuybrushX. We have already discussed this internally and we plan on this, but it will take some time.

Good news, thank you for your fast feedback :-)

I would still like to get some community feedback on the current docs hence I'm not closing it.

If you prefer a new issue or another place for this please let me know.

**Comment by devendran-m** [comment]
Hi @GuybrushX , thank you very much for your feedback and suggestions. Once we have finalised the plan and necessary epics/stories we will share it with you and the community via this repo. Until then you can keep this issue open and we will track the progress against it.

**Comment by ACStoneCL** [comment]
Closed as complete.

**Comment by GuybrushX** [comment]
@ACStoneCL Since you closed that issue:
Where are the graphics please?

**Comment by ACStoneCL** [comment]
@GuybrushX You can find the images produced in [this PR](https://github.com/casper-network/docs/issues/631), which ultimately made their way into the [concepts](https://docs.casper.network/concepts/) section in various ways.
