### ISSUE TITLE
Understand & update the multi-sig tutorial

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#57]
The tutorial needs to be refershed. Understand what has changed from our training materials and make updates, or open new cards for the following sprint.

Also, incorporate this suggestion from Jan to extend the multi-sig tutorial with this info:
https://github.com/casper-network/casper-node/blob/dd260c86aad94ea3a9e958080558778e8aee9f40/types/src/account/error.rs#L52-L63. Jan says: "Today I was asked about error 6 and found out this is pretty important information from my perspective that should be documented at least in tutorial."

Also, we have feedback from one of our hackathon users:
![Update multi-sig tutorial.png](https://images.zenhubusercontent.com/60785891648deb2076a7ddc1/49153a87-11bd-42dc-8c11-c6b9cca54b2b)

**Comment by ipopescu** [comment]
Moving this to mid-December and adding a suggestion from Jan to explain the error codes.

**Comment by GloreenS** [comment]
Created a new task #202 to cover documenting an example for the keys-manager contract.
