### ISSUE TITLE
Add section about using nctl with a private network configuration

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#570]
Currently, we've discussed how to setup a private network, but we haven't provided much information on testing the settings of a private network using nctl.

The objective of this ticket is to add a section about testing the settings of a private network using nctl.

**Comment by ipopescu** [comment]
This ticket is lower pri.

**Comment by ACStoneCL** [comment]
Testing for private networks is covered [here](https://docs.casper.network/operators/setup-network/genesis/), closing this as unnecessary.
