### ISSUE TITLE
Localization (JP) - Add Japanese translated files to the docs

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#573]
Receive the Japanese translation from the community and add it to the docs repository: https://github.com/casper-network/docs. Test the site and publish the content.

**Comment by ipopescu** [comment]
@devendran-m, please prioritize this, we need it for the meeting in August with the Broadleaf team.

**Comment by ACStoneCL** [comment]
This is no longer relevant. If this becomes a priority, we can open a new ticket.
