### ISSUE TITLE
Describe cost per KB in CSPR, block limits & max block size values and explain how to get and inspect the chainspec for a given network

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#581]
Describe in the documenation that the;

1. details like **cost per KB in CSPR**, **block limits** and **maximum block size** values are network specific
2. explain how to get and inspect the above details in the chainspec of a given network
3. caveat in there that this is for the public network with a section that includes Casper Mainnet details

**Comment by ACStoneCL** [comment]
Closed as complete [here](https://docs.casper.network/operators/setup-network/chain-spec/#wasm)
