### ISSUE TITLE
Document Highway Consensus Protocol

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#585]
The aim of this ticket is to document in detail the Highway Consensus Protocol.

**Comment by devendran-m** [comment]
Hi @Buddhika-Pathirathna , please reach out to the SME @afck for the presentation with infographics that he may have and use it as input for this ticket.

**Comment by Buddhika-Pathirathna** [comment]
> Highway Consensus Protocol.

Sure Dev, I will start on this and are there any other resources to refer ?

**Comment by devendran-m** [comment]
> > Highway Consensus Protocol.
> 
> Sure Dev, I will start on this and are there any other resources to refer ?

Hi Buddhika, afaik the presentation that @afck prepared will be the first input to start with. In parallel, we will review and identify other supporting resources for this.
