### ISSUE TITLE
Tutorial on setting up and managing a private Casper Network

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#59]
Explain how to set up a private network, what are the parameters, how they can be configured, how to let a node join in a private network (after it started), how do you manage permissions, how to exclude a node after the network started.
- Michal has a PR open and it is best to work with him to document the chainspec values that relevant to private networks

**Comment by ipopescu** [comment]
@ramujin the card was moved to high priority with the request from Ed to be completed this sprint, so we removed your assignment. One of the tech writers will take this on in the coming sprint. cc @ashok-cl

**Comment by ramujin** [comment]
Sounds good @ipopescu. This was the information that I had received from Joe regarding the process, but I hadn't had a chance to investigate it yet:

> Setup from here: https://github.com/casper-network/casper-node/pull/2883
> [core]
> allow_auction_bids = false
> [highway]
> compute_rewards = false
> 
> Should give you the config I [Joe] used for our private network:
> curl -JLO [genesis.casperlabs.io/private-test/1_0_0/config.tar.gz](http://genesis.casperlabs.io/private-test/1_0_0/config.tar.gz)
> Administrators on accounts.toml is new.
