### ISSUE TITLE
Investigate adding borders to images in markdown

### ISSUE THREAD

**Issue by GloreenS** [casper-network/docs#60]
Find out a way to add a grey-line border to images in markdown. 
Identify if any CSS changes are required.

This is wrt to requirements identified in 
https://github.com/casper-network/docs-app/pull/37

**Comment by ipopescu** [comment]
@devendran-m we should close this card, it is very, very old. Even before Nov 2021 it was sitting in another repository for several months.

**Comment by devendran-m** [comment]
Checked with @GloreenS and closing this as it's not an immediate priority. If a need arises in future, a new card will be created.
