### ISSUE TITLE
Documentation on Session code vs. Contract code

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#609]
- Create a single document focused on the difference between session and contract code
- Examples of session code that does not call a contract (i.e. calls a system contract instead.). 
- Usable, simple example code for both types. 
Note - Use delegate client code as an example for the above

**Comment by ipopescu** [comment]
This card needs to be reviewed, and Karan will not be available at the end of the sprint. The work is complete, but we are moving this to next sprint to allow for the review.
