### ISSUE TITLE
Create a document on how to work with Wasm and Casper for other languages

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#610]
Create a document on how to work with Wasm and Casper for other languages like Java, Python and other Wasm-compatible languages.

Definition of Done - A document that can be used by the developer community that will explain the steps on how to work with wasm and Casper for other languages.

**Comment by ACStoneCL** [comment]
Completed by the DevPortal team [here](https://docs.casper.network/developers/dapps/sdk/client-library-usage/)
