### ISSUE TITLE
A more readable node schema

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#62]
The JSON-RPC API is documented in an OpenRPC format and can be provided by any running node.

You can retrieve the schema by e.g. running

casper-client list-rpcs -n http://<IP>:7777
where IP is the public IP of a running node. You can find e.g. the testnet nodes' IPs at https://casper-explorer.dev.make.services/tools/peers.

If you don't have the casper-client installed, you can do that via

cargo install casper-client
We're working on presenting the schema in a more human-readable form than raw JSON. I hope @ipopescu can link the relevant ticket for that work.

Linked ticket: https://github.com/casper-network/casper-node/issues/2060#issuecomment-953155594.

E.g. https://substrate.dev/rustdocs/latest/sc_service/index.html

**Comment by ACStoneCL** [comment]
This card is redundant with [roadmap#121](https://github.com/casper-network/roadmap/issues/121), so I'm self-assigning so I can manage it concurrently.

**Comment by devendran-m** [comment]
Closed via #266
