### ISSUE TITLE
Discovery: look into translated files in Docusaurus

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#621]
Take a couple of hours to look into translated files for the docs and let Luca/SRE know the results.

**Comment by ipopescu** [comment]
We have met with the BL team creating the content (also hosted [here](https://casper.blockchaintechlab.jp/casper-network/documentation/developers/writing-contracts/session-code/)) and I am looking into adding it locally to see if it's possible.

**Comment by ipopescu** [comment]
**Summary**: it was not straightforward for me to add translated files to the current docs platform. 

I recommend **creating a 13-point card to get the translations working** locally and in our integration environment with help from our SREs. More details below. @devendran-m please create this card before docs grooming tomorrow. @bradjohnl  and @TomVasile, FYI.

I gathered files in Japanese (with the latest content translated) from our partner and attached them [here](https://drive.google.com/file/d/11AAYd0wXAEQn6q2ZAit323ZJpU9X_Bjh/view?usp=sharing).

I reviewed the Docusaurus documentation, including the docs README and the structure of our repository.
https://docusaurus.io/docs/i18n/tutorial 
https://docusaurus.io/docs/i18n/introduction
https://docusaurus.io/docs/i18n/git#prepare-the-docusaurus-site

I tried to add the files and build the site locally.
I have worked in this branch: https://github.com/casper-network/docs/commit/bb005aa66aaa1fdca3ef9e2c442b7d486088ab10

I was able to change a few settings, build and run the site here:
http://localhost:3000/ja/ 

But the translated content is not getting picked up on the getting started page:
http://localhost:3000/ja/dapp-dev-guide/writing-contracts/getting-started/

Additional findings: we have a lot of unused and obsolete files in our docs repository. It is very bloated. I believe we opened a card to clean this up. 
@devendran-m  could you please check and add this card if it doesn’t exist? We really need to clean up any unused files and blog repositories and directories/files that don’t make sense. The developer who helped us create this repository was just trying things out and did not clean them up before production-alizing it and handing it over.

<img width="237" alt="Screen Shot 2022-08-18 at 12 04 49 PM" src="https://user-images.githubusercontent.com/4185994/185371005-8f2043c9-c8aa-4cec-9590-3c66f7c1301d.png">


<img width="1459" alt="Screen Shot 2022-08-18 at 12 04 43 PM" src="https://user-images.githubusercontent.com/4185994/185370964-025ca4bd-b115-426c-acb3-36cbd273fc20.png">

**Comment by devendran-m** [comment]
Note - Created this for resolving translation issue - https://github.com/casper-network/docs/issues/641
