### ISSUE TITLE
Docs - Architecture infographics: Execution Semantics

### ISSUE THREAD

**Issue by gskerry** [casper-network/docs#631]
SA to produce infographics supporting and supplementing https://docs.casperlabs.io/design/execution-semantics

**Comment by hectoratcasper** [comment]
Here are the artifacts produce for this iteration: 

@gskerry please review them and close ticket if appropriate

![image](https://user-images.githubusercontent.com/102557486/190035905-4b19ba08-2e39-4387-8d2b-4c7382e03a13.png)


![image](https://user-images.githubusercontent.com/102557486/190035876-0e9921ff-03d2-4cc8-88ba-e9cb79cdbed0.png)


![image](https://user-images.githubusercontent.com/102557486/190035853-bf291b5e-219e-4786-8006-da17bfea18f1.png)


![image](https://user-images.githubusercontent.com/102557486/190035832-fc1218cd-1a43-4e45-a401-5f5ad8e38350.png)


![image](https://user-images.githubusercontent.com/102557486/190035813-4920a448-224f-4c83-b233-a5cdb02231f6.png)


![image](https://user-images.githubusercontent.com/102557486/190035734-8f27111a-02ef-41e6-9c02-daa2d26d725e.png)

**Comment by devendran-m** [comment]
> Here are the artifacts produce for this iteration:
> 
> @gskerry please review them and close ticket if appropriate
> 
> ![image](https://user-images.githubusercontent.com/102557486/190035905-4b19ba08-2e39-4387-8d2b-4c7382e03a13.png)
> 
> ![image](https://user-images.githubusercontent.com/102557486/190035876-0e9921ff-03d2-4cc8-88ba-e9cb79cdbed0.png)
> 
> ![image](https://user-images.githubusercontent.com/102557486/190035853-bf291b5e-219e-4786-8006-da17bfea18f1.png)
> 
> ![image](https://user-images.githubusercontent.com/102557486/190035832-fc1218cd-1a43-4e45-a401-5f5ad8e38350.png)
> 
> ![image](https://user-images.githubusercontent.com/102557486/190035813-4920a448-224f-4c83-b233-a5cdb02231f6.png)
> 
> ![image](https://user-images.githubusercontent.com/102557486/190035734-8f27111a-02ef-41e6-9c02-daa2d26d725e.png)

Nice-looking artefacts
