### ISSUE TITLE
[CEP-78] Document examples/use cases describing each modality's usage

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#638]
User Story: As a user, I would like to understand through examples or reference use case implementations;
- how each modality can be used
- when to use a certain modality
- what are the advantages of using a specific modality
- what are the disadvantages if any and how to overcome it

Definition of Done: Documentation artefact/content clearly explaining the usage of modality, differences, advantages and disadvantages of choosing a specific modality through use case references/examples

**Comment by devendran-m** [comment]
Current Readme covers the required information. Closing as won't do, based on the grooming on Sep 14th.

**Comment by ipopescu** [comment]
@devendran-m @darthsiroftardis this was closed in my absence, after we discussed it on slack and on a previous call. We need such examples for training, and they would also be useful in our docs. Please provide these examples when you have time - not urgent but important.

**Comment by ipopescu** [comment]
Moved to Pro Serv https://github.com/CasperLabs/ProServices_General/issues/117.
