### ISSUE TITLE
Add translated pages to the documentation website

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#641]
**Problem Statement:** The process to host translated files on the current documentation website is not working as expected, even after following the instructions specified by Docusarus. 

**User Story:** The objective of this ticket is to seek the SRE team's help and work with them to get the translations working locally and in our integration environment.

More information on the efforts taken so far can be found on the discovery/analysis work done by @ipopescu via the ticket https://github.com/casper-network/docs/issues/621

**Definition of Done:** 
1. A fully functional translated documentation website in a specific language. 
2. Clearly defined process to translate and/or host translated contents on the specific translation site/pages.

**Comment by devendran-m** [comment]
@sacherjj , could you let me know if anyone in SRE team can help us with this

**Comment by ACStoneCL** [comment]
Closed as irrelevant for now. If we want to start a new translation initiative, we can open a new epic.
