### ISSUE TITLE
Create a documentation explaining what a dApp is

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#642]
**User Story:** As a new entrant I would like to go through the documentation and understand what a dApp is in detail. I would like to gain an understanding of the below contexts by going through the dApp documentation;
- A dApp definition
- What is special about dApps?
- How is it different?
- Its basic constructs, differentiation factors, working principles

**Definition of Done:** An introductory documentation content clearly and comprehensively that explains What a dApp is.

**Comment by ipopescu** [comment]
This needs to move to next sprint due to card #609.
