### ISSUE TITLE
Docs Improvement: Include additional details about `Address` references in `Design` section

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#646]
This Documentation Improvement ticket aims to provide additional clarity on `Address` / `AccountHash` references on the [`Design`](https://docs.casperlabs.io/design/) section of the website.

Please find the additional information explaining what an account hash is, how it is derived from the currently supported variants of Public Key, and how it abstracts away from having multiple Public Key schemes that vary in length, etc. 

Please refer to the additional info in question 3 on the document [here](https://docs.google.com/document/d/1TOJRfAFcRMsOUhxwfEki0Rdj3YYBdamK017n6-Z9ES4/edit#) and add the respective sections on the [`Design`](https://docs.casperlabs.io/design/) page of the documentation website.

**Comment by RitaMAllenCA** [comment]
@ipopescu can you provide an estimate? I have it marked for the current sprint, but let me know if that sounds achievable

**Comment by ipopescu** [comment]
@RitaMAllenCA and I discussed keeping this out of the sprint.

**Comment by ipopescu** [comment]
@devendran-m for this ticket, is there any more information that what [here](https://docs.google.com/document/d/1TOJRfAFcRMsOUhxwfEki0Rdj3YYBdamK017n6-Z9ES4/edit#) is linked and pasted below? I don't have access to the Slack link, and maybe I don't need to.

> Question 3:  What is the difference between Public Key and Account Hash?
> The question originated in a Slack conversation thread - https://casperassociation.slack.com/archives/CDXBCHB6W/p1660936826555269
> 
> Answer:
> PublicKey is a public key. We currently support 2 variants - i.e. ed25519 and secp256k1, with the intent to support more. **An AccountHash is a derived hash from a PublicKey of any supported variant. By doing so, it abstracts away from having multiple Public Key schemes.** 
> 
> **The main reason for doing this is, Public Keys can vary in length, but Casper’s Global State Trie store requires all keys of the same kind to be the same length. For instance, ed25519 public_key_hex is 64 chars whilesecp256k1 is 68 chars and 32 and 33 bytes a the hash level respectively.  So, Account Hash “fixes” that by being a 32-byte length derivative.**
> 
> Address on the other hand is a more general term. AccountHash, ContractHash, ContractPackageHash, and ContractWasmHash are all a kind of "Address". So, while it is technically correct to refer to AccountHashes generally as “Addresses”, it is a bit ambiguous. For instance, AccountHash is an Address, not all Addresses are AccountHashes.
> 
> **casper-client account-address can generate the account address / account hash from public_key_hex.**

**Comment by ipopescu** [comment]
If this is all the information requested to be included in the docs, we are already covering most of what is requested. I will go through the design section and some other pages to see if I can highlight some of the information and make sure it's clear. We can also add something to the FAQ.
So, this ticket needs 1-2 points to add some clarifications.

**Comment by devendran-m** [comment]
Hi @ipopescu , I have pasted the Slack conversation details below Question 3.  (Please ignore the formatting). That was the original conversation which resulted in Q3 in FAQ.

**Comment by ipopescu** [comment]
This is very helpful, thank you @devendran-m!

**Comment by ipopescu** [comment]
@RitaMAllenCA I am adding this in the sprint since it's very much related to my current work #404 and since I am blocked on #805.
