### ISSUE TITLE
Add 'Search' to specific sections

### ISSUE THREAD

**Issue by Buddhika-Pathirathna** [casper-network/docs#65]
Check the ability to add 'Search' functionality to a specific section.
This is to check the possibility of searching for any detail within a specific section of the developer portal; a kind of localized/in-line search.

_**For an example:**_
This requirement was raised when discussing the structure and organization of the FAQ section of the developer portal. If a user landed FAQ section and he/she is not sure in what category the question should be looked for, it is good to have an in-line search within the FAQ section to check the details.

**Comment by sd-ditoy** [comment]
I've took some time to investigate if this would be possible with the integrated algolia search. Which sadly is not the case.

I have a suggestion though, which might achieve this as well, without us having to reinvent the search wheel for the entire documentation.

Wouldn't it be more useful to have all FAQ pages combined to one page ( General, Enterprise, Developers, Validators ) and just structure them accordingly in a singular markdown file?

This would allow us to just build a clientside search (with the help of something like Bloodhound.js, see: https://github.com/swiftcarrot/bloodhound), specifically for the content of that page.

**Comment by ipopescu** [comment]
Is this still needed, or can we close it, @Buddhika-Pathirathna and @devendran-m ?

**Comment by devendran-m** [comment]
Given that we have improved the overall search facility thanks to @bradjohnl, @Buddhika-Pathirathna and I discussed and agree on closing this ticket as 'already addressed' in the overall Documentation Site level search improvements. 
cc: @ipopescu
