### ISSUE TITLE
 Update protocol documentation

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/docs#660]
After the current 1.5 push, the networking protocol documentation (see #3185) needs to be updated to reflect any changes made.

**Comment by RitaMAllenCA** [comment]
@ACStoneCL @darthsiroftardis this is a "passive" ticket - I am going to close it.   As Ed was saying yesterday, documenting the protocol requires a level of sophistication I am not sure we can afford in the near future - or if it even pays off.   If we decide differently we can create another ticket.  cool?

**Comment by ACStoneCL** [comment]
@RitaMAllenCA That sounds like a plan to me.
