### ISSUE TITLE
Document a clearer workflow for how to use `dictionaries`

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#683]
Document a clearer workflow for how to use `dictionaries` (current docs are high level).

Feedback from a user, which is a driver for this ticket;

> Currently, the docs have only [this information](https://docs.casperlabs.io/dapp-dev-guide/dictionaries/) pertaining to dictionaries, which doesn’t help developers at all in terms of interacting with dictionaries using the Rust client. When trying to use the `casper-client get-dictionary-item` command, it is unclear what the arguments need to be based on what’s in the docs above.
> In my case, I was repeatedly trying/modifying/guessing at variants of my arguments because I kept receiving the error: `failed to parse the dictionary identifier`. It turned out that it was because I was not prefixing the contract hash with `hash-` when supplying it as an argument, but the error misled me to keep tweaking my `dictionary-name` and `dictionary-item-key` arguments until, out of sheer frustration, I dug into the source code of the JS SDK to see if I could find any clues about how to debug my error. That’s when I noticed the prefix. Otherwise, I would have been utterly stuck with no direction.
> 
also see this ticket for additional information: https://app.zenhub.com/workspaces/engineering-l2-62618a6423afe100128e4656/issues/casper-network/docs/684

**Comment by RitaMAllenCA** [comment]
@darthsiroftardis @ACStoneCL I understand that we are getting inquiries around CEP-78 that come down to fundamental changes in the model we use.  However, we still must be clear on how to interface with what we have built if we want to facilitate adoption.  Given that NFTs are stored in dictionaries - what do you think about prioritizing them?  Would this area of documentation be useful to NFT application devs?
