### ISSUE TITLE
Create a document on listing ERC-20 type tokens built on Casper

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#685]
Aim: To create a detailed documentation explaining how to list ERC-20 type tokens built on Casper.

The documentation should be based on the analysis that explains  
1. What the workflow looks like, and namely what the differences are from Ethereum ERC 20.  
2. Details of listing, workflow and differences from a technical perspective, and see what we can do to reduce the engineering lift as much as possible.

Priority - in 2 - 4 sprints.

**Comment by devendran-m** [comment]
Docs Grooming:10/12: Action>>Dev: Take this up with Piotr & Adrian and see if this can be hosted on casper.network

**Comment by ipopescu** [comment]
I am very unclear on the goal and details for this card. Initial questions:

Listing the tokens where? On an exchange? On a webpage?
What workflow is needed here? How to create these types of tokens?

If the goal is to get a list of the available tokens in the ecosystem, I suggest adding it to the casper.network site, and not in the core documentation. In this case, this task should go back to the Association (Dev, Piotr, Adrian).

If technical workflow documentation is required, then we should improve the documentation already found here: https://github.com/casper-ecosystem/erc20/blob/master/docs/TUTORIAL.md.

**Comment by ACStoneCL** [comment]
Closing this in favor of new tickets that are more specific. This will require dev resources, as to my knowledge it isn't a thing that is currently done.
