### ISSUE TITLE
Move old docs-archive PRs to docs

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#70]
Several PRs from the old docs repository need to be moved to docs-app:
https://github.com/casper-network/docs-archive/pulls?q=is%3Apr+is%3Aclosed+label%3A%22move+to+docs-app%22

Most of the content comes from the hackathon:
<img width="987" alt="Screen Shot 2021-11-26 at 8 10 42 PM" src="https://user-images.githubusercontent.com/4185994/143622525-dd3f0614-ed10-4516-95cd-fc96eb9909f0.png">

**Comment by ipopescu** [comment]
@Buddhika-Pathirathna Do you think you could help me with this next sprint?

**Comment by Buddhika-Pathirathna** [comment]
> @Buddhika-Pathirathna Do you think you could help me with this next sprint?

Sure, Iulia, I will.
