### ISSUE TITLE
Update the session and contract sections

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#704]
After an in-depth discussion, we agreed to do the following updates:
- For session code, demonstrate a wasm-based transfer, then the two-party multi-sig
- For contract code, show the counter code first, then the session (call, multi-sig)
- Restructure the docs to introduce contract code first.
- Test and update the code samples for writing and testing session code.
- Test and update the code samples for writing and testing contract code.
- Review the documentation PR with the dev team, Adam, and incorporate their feedback

**Comment by ipopescu** [comment]
@RitaMAllenCA I updated the estimate to an 8.

**Comment by ipopescu** [comment]
This task has been larger than estimated (13+ points) due to having to update and rewrite close to 1,000 lines in the documentation. The content that was there before was inconsistent, unclear, duplicated, and was missing key information. 
I have addressed everything except the wasm-based transfer, for which I need some example code from the dev team. I will submit a PR for what I have, as it is a lot to review in one go. During the review, I will look into the wasm-based transfer to accomplish it at the end of the sprint.

**Comment by RitaMAllenCA** [comment]
@ipopescu Hi Iggy-pop!  How about if we close this ticket with your PRs and create a new one for the next sprint to capture the outstanding WASM-based Transfer?  No reason you can not start on it now, but we will allow it to roll.  THoughts?

**Comment by ipopescu** [comment]
@RitaMAllenCA let's see where I'm at by grooming today. I am waiting to hear back from Zoltan. If I don't have the info I need by then, we can open a new card.
