### ISSUE TITLE
Deploy serialization example is insufficient

### ISSUE THREAD

**Issue by saitgulmez** [casper-network/docs#714]
Deploy serialization [example](https://docs.casperlabs.io/design/serialization-standard/#deploy-serialization-at-high-level) has lack of some details in that  there are no **target** and **id** args and  **amount** is specified as I32 value and type  instead of U512 value and type.

**Comment by ACStoneCL** [comment]
Good catch, we'll go through and revamp this section of the documentation to be more accurate.
