### ISSUE TITLE
Docs-Create Architecture Infographics:Global State [Timeboxed]

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#719]
Docs-Create Architecture Infographics:Global State [Timeboxed]

**Comment by lhg9865** [comment]
![Global State ](https://user-images.githubusercontent.com/108345598/195645696-d8697f0e-de99-4320-b458-d6aeee80f137.png)

**Comment by lhg9865** [comment]
The infographics have been merged into a slide and sent to Karan for review.
