### ISSUE TITLE
Add the transfers guide to docs-app

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#73]
We have this document in a google doc: https://docs.google.com/document/d/1wC6z7xNKj7HHSxUvuB7Z4pVUdQ2qIv_p/edit
This card focuses on making the content more general to describe transfers on both Testnet and Mainnet.
The section about the Faucet will remain only for the Testnet.

**Acceptance criteria to close this card:**
1. Review the document
2. Re-structure the document to generalize it
3. Add the content to docs-app in the user guides section: https://casper.network/docs/workflow#what-is-casper
4. Submit a pull request for review

**Comment by ipopescu** [comment]
Hi @piotr-dziubecki, @GloreenS completed the work, but I wasn't able to assign her to the card.

**Comment by GloreenS** [comment]
Merged PR #52 and opened new ticket #138 to generalize the content.
