### ISSUE TITLE
Extend best practices documentation around testing to include dockerized `nctl`

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#730]
As a Technical writer, explain the benefits of using dockerized NTCL in [Setting up a Local Network with NCTL | Casper](https://docs.casperlabs.io/dapp-dev-guide/building-dapps/setup-nctl/) section. 
- Extend the best practices around testing, to include Make team's dockerized NCTL and its usage.
- Explain the benefits of using dockerized NCTL as elaborated in this [README](https://github.com/make-software/casper-nctl-docker) section
- Include the advantages of how it can reduce onboarding time dramatically and can be used locally without risking their systems-

**Comment by RitaMAllenCA** [comment]
Do we want to do this?

**Comment by ipopescu** [comment]
We discussed this in grooming, and it is the creator's responsibility (in this case, Make) to provide the documentation. They are already providing the documentation here: https://github.com/make-software/casper-nctl-docker.
I think we need to close this ticket @RitaMAllenCA.
