### ISSUE TITLE
Restructure the Transfer Workflow Content and add sign-deploy command

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#74]
Test and update the transfer workflow: https://docs.casperlabs.io/en/latest/workflow/transfer-workflow.html

Restructure the topics in the How To's section related to Transferring tokens. 
Create a parent topic introducing token transfer in general and branching out to direct transfer, multi-sig deploy transfer, and checking the account balance.
Transferring tokens
- Direct transfer
- Multi-sig deploy transfer
- Verifying the transfer (these commands are common to both the topics)
Add sign-deploy command to the Multi-sig Deploy transfer topic.

**Comment by GloreenS** [comment]
Merged PR #56 with all changes.
