### ISSUE TITLE
Expand Explanation of Dictionary Keys

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#764]
Expand information in the [Understanding Dictionaries](https://docs.casperlabs.io/dapp-dev-guide/dictionaries/) document to thoroughly explain the dictionary key itself.

**Comment by RitaMAllenCA** [comment]
@ACStoneCL just saw this and thinking that it may also be part of the dictionary work you are doing next sprint?  If so, let me know if we should close it as related.

**Comment by ACStoneCL** [comment]
@RitaMAllenCA We can definitely fold this into my dictionary work for next sprint.

**Comment by RitaMAllenCA** [comment]
We will do this work as part of #683
