### ISSUE TITLE
Confirmation screen fixes

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/docs#773]
- [x] "You can view the deploy at…" - add deployHash and URL to configurable block explorer
- [x] Under the Token Details, The db model property names (e.g. Make/Model, EngineCapacity, FuelType, Drivetrain) are listed but we need to see the property values here (e.g. whatever the user typed into the previous screen should show up here). This should be variable, based on whether it's a vehicle or e-bike.
- [x] Popup Message confirmation: The link to the block explorer should open in a new tab

**Comment by DorianKwan** [comment]
This had some unforeseen technical challenges and was more suited to a 5 rather than a 3.  I've upped the story points to reflect
