### ISSUE TITLE
Expand Dictionary Key Definitions

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#799]
As per the following Slack excerpt;

![image](https://user-images.githubusercontent.com/97986246/206004110-653a65d9-613e-4d59-8271-8595c2a5cdd4.png)

Thoroughly explain how dictionary keys are defined in the docs.

**Comment by AlexanderLimonov** [comment]
Sure, let me try. Our dictionary keys have a very particular format which, in practice, requires a contract-specific encoding of some "natural" keys (like an account hash + a token index) into an actual dictionary key understood by the system. My ask here is to expand the description of what kind of objects the dictionary keys are and how to form them in typical use cases (e.g., examining contents of CEP-78 contract dictionaries using state queries)
