### ISSUE TITLE
Updating the automation for the documentation

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#800]
We are having [discussions](https://casperlabs-team.slack.com/archives/C0135SDEGUC/p1670319426112909) on revisiting and updating the automation for the documentation site. From Luca:

I can see that the staging site is still there and getting updated. I thought it has been removed or maybe I am wrong then. We could change the pipeline to:
- Remove the staging site from AWS.
- Remove the staging deployment.
- Start prod deployments directly when PRs are merged to dev
- Remove the PR-bot app and logic.
- and we get rid of the main branch.

**Acceptance criteria:**
- hold a follow up meeting (30 min)
- work with Luca to make the updates
- test and close the card

**Comment by RitaMAllenCA** [comment]
@sacherjj @bradjohnl we need luca's support in the next sprint 12/13/22 - will there be availability?

**Comment by ipopescu** [comment]
Decisions:
- Remove the staging site
- Remove main branch
- Keep the workflow and merge to dev => the ‘master’ branch
- When working on features, need to manually and periodically rebase
