### ISSUE TITLE
WASM Based transfer documentation update

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#813]
- For session code, demonstrate a wasm-based transfer
- Test and update the code samples for writing and testing session code.
- Review the documentation PR with the dev team, Adam, and incorporate their feedback

**Comment by RitaMAllenCA** [comment]
@ipopescu @deuszex this is a lightweight ticket to continue the work Ilulia did in the Dec 13 sprint.  She needs Zoltan's help to finish up the wasm-based transfer documentation.   Given the holiday PTO schedules, this is a good time to finish up this work.

**Comment by ipopescu** [comment]
I will reduce the estimate based on what I understand so far to 3 points.

**Comment by ipopescu** [comment]
@darthsiroftardis, I still need clarity on the requirement to demonstrate session code invoking a “wasm-based transfer” for these [docs](https://docs.casperlabs.io/dapp-dev-guide/writing-contracts/session-code/).
I thought that a wasm-based transfer would use a contract such as this: `casper-node/target/wasm32-unknown-unknown/release/transfer_to_account.wasm.`

We also have these APIs:

- https://docs.rs/casper-contract/latest/casper_contract/contract_api/system/fn.transfer_to_account.html
- https://docs.rs/casper-contract/latest/casper_contract/contract_api/system/fn.transfer_to_public_key.html
- https://docs.rs/casper-contract/latest/casper_contract/contract_api/system/fn.transfer_from_purse_to_purse.html
- https://docs.rs/casper-contract/latest/casper_contract/contract_api/system/fn.transfer_from_purse_to_account.html
- https://docs.rs/casper-contract/latest/casper_contract/contract_api/system/fn.transfer_from_purse_to_public_key.html

Do you want to see this in the documentation?

> In this example, we use session code to perform a transfer using the [transfer_from_purse_to_purse](https://docs.rs/casper-contract/latest/casper_contract/contract_api/system/fn.transfer_from_purse_to_purse.html) system function. The entire session code is available in [GitHub](https://github.com/casper-network/casper-node/blob/dev/smart_contracts/contracts/bench/transfer-to-purse/src/main.rs), but this is its `call` function:
> 
> ```rust
> #[no_mangle]
> pub extern "C" fn call() {
>     let target_purse: URef = runtime::get_named_arg(ARG_TARGET_PURSE);
>     let amount: U512 = runtime::get_named_arg(ARG_AMOUNT);
> 
>     let source_purse = account::get_main_purse();
> 
>     system::transfer_from_purse_to_purse(source_purse, target_purse, amount, None)
>         .unwrap_or_revert();
> }
> ```
