### ISSUE TITLE
Remove use of /rpc after node address in docs

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#818]
This has become more urgent with the soft release of CEP 1.1 over the holidays.  

See the quick discussion here: https://casperlabs-team.slack.com/archives/C0135SDEGUC/p1672253205265429

**Comment by RitaMAllenCA** [comment]
@ipopescu Hi - created this ticket to specify the work you are doing to support the docs for CEP-1.1.  Feel free to estimate it and close it, etc....

**Comment by ipopescu** [comment]
Half of this ticket is addressed in [this PR](https://github.com/casper-network/docs/pull/823/files). However, I need to speak to the developers regarding instances where SDK code uses the port with /rpc.
