### ISSUE TITLE
Discover best practices for Casper contracts

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#82]
Create a best practices wiki page for smart contracts and start gathering information (this is only the discovery phase). 
As part of a future sprint: receive guidance and information from Karan and the development team. Add the final guide to the docs repository.

**Comment by ipopescu** [comment]
Moving this card out of the sprint as I need more background information. I have taken up the equivalent amount of points documenting deploys and events.

**Comment by devendran-m** [comment]
Documenting best practices will be covered in #298 
Closing this issue.
