### ISSUE TITLE
Question: how to get token decimals using the sdk

### ISSUE THREAD

**Issue by DevAseel** [casper-network/docs#820]
Hello everyone,

Apologies in advance if this is not the right place to ask questions.

I'm currently using the [casper sdk ](https://docs.casperlabs.io/sdk/), and i'm trying to get the token0 and token1 decimals for the pair created events. I can see that the sdk has two methods that I can use `getDictionaryItemByURef` & `getDictionaryItemByName`, but I'm not sure about the parameters that the method accepts, if someone could clarify that please.

This's an example of pair created event that i'm looking at: 
https://cspr.live/deploy/fc1504895feaafdb992c3ef49c8481de4911daccb9bff0c1f08d487df801d5f3

**Comment by RitaMAllenCA** [comment]
@hoffmannjan is this something Ryo can respond to?

**Comment by DevAseel** [comment]
@RitaMAllenCA Thank you for your response. This's no longer an issue, I used the `blockState` method. Closing this for now 😁
