### ISSUE TITLE
Create a Program that eases the DApp developer start

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#832]
Create a program that eases the dApp development start. This should be a CLI (command line) program generating:

Rust smart contract project
where Cargo.toml is prepopulated with commonly used dependencies when developing smart contracts on CasperLabs chain.
template for tests
template for the smart contract
scripts for deployment against TestNet/local chain
scripts for calling the contract from the CLI - for local testing
subproject with simple frontend that interacts with the dApp:
simple form that allows user to fill in the arguments to call the contract
[optionally] use different types: integer, string, bool -(checkbox)
[optionally] Casper branding - colors, logos, etc
integration with Signer - i.e. it should be possible to sign the form (as a transaction) and send it to the chain (local or TestNet,
depending on the env config)
Example:
There’s a Terra repo that implements the above to some extent
https://github.com/terra-money/terrain

NOTE: This can also be made into a grant idea - with a sufficient description, we can offer people to do this for CasperAssociation/CasperLabs in exchange for a grant.

In addition to the above, @hoffmannjan added - SDK and Signer related work as art of the dApp development bootstrap.

**Comment by ACStoneCL** [comment]
Considerable work has been done to the [dApp section](https://docs.casper.network/developers/dapps/) on the documentation site. If we need any additional resources, we can start a new initiative/epic for it.
