### ISSUE TITLE
Document JSON RPC API

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#85]
It would be best to check with Ed and Joe Sacher if we should document this API, or if we should keep it hidden.
If we need to document it, add a link and a brief introduction to our JSON RPC API in the main documentation: http://casper-rpc-docs.s3-website-us-east-1.amazonaws.com/.
Probably the best place to add this is here: https://docs.casperlabs.io/en/latest/workflow/index.html#developer-guides
and here: https://casper.network/docs/workflow#developer-guides

**Comment by devendran-m** [comment]
Closed via #266
