### ISSUE TITLE
Update diagram comparing session and contract code

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#854]
Update the [diagram](https://docs.casperlabs.io/dapp-dev-guide/writing-contracts/contract-vs-session/#comparing-session-and-contract) comparing session and contract code, based on this [Slack discussion](https://casper-labs-team.slack.com/archives/C01U1AVERFB/p1674112707683119?thread_ts=1673352637.739449&cid=C01U1AVERFB).

**Comment by ipopescu** [comment]
The new diagram is out for review: https://www.figma.com/file/IY89UKxEC43Pq4f7vGBpHB/Casper-Session-vs-Contract-(Update-April-2023)?node-id=0%3A1&t=Ge3Vfo5XI0gA01Lo-1

The current diagram is in the docs here: https://docs.casper.network/concepts/session-code/.

Notes from [a Slack discussion](https://casper-labs-team.slack.com/archives/C01U1AVERFB/p1673370708862179?thread_ts=1673352637.739449&cid=C01U1AVERFB):
- ModuleBytes deploy variant: call as a starting point
- StoredContractByName/Hash deploy variant: entry point as a starting point
- For contracts, internally, we create a session context for the account, bypass `call` and invoke the specified entry point. If session logic calls one or more entry points during its execution, those entry points are on one or more contracts, and each will execute using the context of that contract

Requests to update the diagram:
1. remove the call portion entirely from the smart contract side
2. instead of having the code box inside the context box, have them be separate boxes. The context does not contain the code and the code does not contain the context. The code is what is loaded into a VM and invoked by the runtime and the context is a state bag initialized from global state, then used by that runtime, and any relevant changes to the context are then persisted back to global state at the very end when the deploy is committed.

Related documentation:
https://docs.casper.network/developers/writing-onchain-code/calling-contracts/

**Comment by ramujin** [comment]
Ed shared some [valuable insights on Slack](https://casper-labs-team.slack.com/archives/C01U1AVERFB/p1681498075330839) on the flow diagram that probably means we need to scrap this diagram and start fresh making a few of them to capture all that he conveyed.

**Comment by ipopescu** [comment]
@ramujin @ACStoneCL: Given all the additional feedback, I will open a new card for that work and request one of the architects to be involved. Since I have addressed the original request and the diagram is still live on the site, I should submit what I have. If you think we should remove the diagram, please let me know.

**Comment by ipopescu** [comment]
The follow-on ticket is here: https://github.com/casper-network/docs/issues/1085.
