### ISSUE TITLE
Ask Google to recrawl the docs site

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#892]
Google search is still indexing old pages. We should look into the instructions below and ask Google to recrawl the docs site. We need to repeat the process anytime we change the links.

Follow these instructions:
https://support.google.com/webmasters/answer/7041154?hl=en

**Comment by ipopescu** [comment]
Assigning to @Adrian-Wrona for proper assignment

**Comment by bradjohnl** [comment]
@ipopescu So there are 3 solutions here:

## Fix the links this one time
Probably just a matter of generating the sitemap and uploading it to Google. 

For this, we need someone who has access to the Google Search Console for the website. 
This is the fastest solution, but does not do anything to address future issues automatically.

## Generate the sitemap automatically and push it to Google through the Search Console API in the CI
Would require some setting up. Probably a 8-13 pointer. This should be done anyways as the best approach is to do both this and server-side redirects to redirect old links (bookmarks, links in blogs and sites, etc..).

## Client-side redirects through Docusaurus plugin
Quicker solution than server-side redirects, not as effective as server-side redirects for SEO, performance and other things. Probably a 5-8 pointer.

## Server-side redirects through Netlify and/or Cloudflare workers and/or S3
If we move the website to AWS S3 we can easily set up server side redirects with redirection rules and the costs would be marginal, though more than GithubPages which is free. 

Other solutions include Netlify or Cloudflare workers. 

S3 solution would include S3 setup, migration from GH Pages, pipeline changes, setting up redirects on S3. Probably a 8-13 pointer.

**Comment by bradjohnl** [comment]
@Adrian-Wrona @RitaMAllenCA 
If I am doing this, then I need the confirmation that other projects I am working on in parallel will be temporarily set aside.

Namely:
- Catchy / MiracleDevs - CasperAssociation's developer portal infrastructure.
- Membership Portal Backend dockerization for K8S infrastructure.

**Comment by bradjohnl** [comment]
Otherwise we just update the sitemap that would fix the errors we have now, and that's it.
The plugin is already active and the sitemap is generated at every deployment:
https://github.com/casper-network/docs/blob/gh-pages/sitemap.xml

The person who has access to the Google Search Console has to upload this:
https://github.com/casper-network/docs/blob/gh-pages/sitemap.xml

**Comment by bradjohnl** [comment]
@RitaMAllenCA @ipopescu PR is ready for review

**Comment by ipopescu** [comment]
Thanks, @bradjohnl for the quick fix. Since the PR is closed, is this it? Or is there a longer-term fix as well? 
Do we leave this card open until someone can update the Google Search Console?

**Comment by bradjohnl** [comment]
I see the search results are still not updated yet on Google.

I talked with @Adrian-Wrona this morning. He has information about the person being able to push the sitemap to Google. He will get in contact with this person who is based in the US, today to have her upload the sitemap.

In the meantime I have also tried to notify google about the new sitemap with a ping request. Let's see if it has any effect in the short term.

Ultimately submitting it to the search console, as I explained should be the surefire way.

**Comment by bradjohnl** [comment]
@ipopescu @RitaMAllenCA @Adrian-Wrona 

Just confirming that Google has re-crawled the site.
I see search results now reflect the new structure.

Sorry @ipopescu for not addressing your question.
We should keep the ticket open as the requirement: "We need to repeat the process anytime we change the links." is not really met and we need to address future structural changes possibly without manual intervention.

In alternative we need to raise awareness, maybe in the PR template, that every structural changes requires pushing the sitemap to Google Search console for them to be visible in a timely manner.

We can think of alternative processes of course.
The robots.txt + correct sitemap generation goes already a great deal and manages to make the crawler refresh the site in a few days.

As I mentioned I did also send a ping to google by calling the URL:
`https://www.google.com/ping?sitemap=https://docs.casperlabs.io/sitemap.xml`

Maybe this helped speed up the process, so we could, for the time being rely on the approach that if the change is structural, we call the URL as part of the PR creation process AFTER the PR has merged and the site deployed. We should mention this in the PR template.

I think that once we agree on a process, we can close this ticket as we are making sure that the sitemap gets refreshed for new applicable changes.
If we want to have more comprehensive solutions, such as API calls to the Google Search Console as part of the CI, we can address that in future issues.

**Comment by ipopescu** [comment]
FYI @adam on this discussion.

**Comment by andrzej-casper** [comment]
Incorporating it into CI/CD should be rather easy: there is [sitemap submit method](https://developers.google.com/webmaster-tools/v1/sitemaps/submit) that could be invoked with `curl` command.

**Comment by ipopescu** [comment]
We are including the solution in the new CI/CD pipeline for the docs:
"Generate the sitemap automatically and push it to Google through the Search Console API in the CI".
