### ISSUE TITLE
Retest redelegate command for 1.5

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#898]
Test the redelegate.wasm when 1.5 gets to integration test. Or, try again with nctl when the dev branch stabilizes. 

Add information about calling the redelegate entrypoint in the system auction directly instead of calling the redelegate.wasm.

The redelegate documentation was delivered with this PR: https://github.com/casper-network/docs/pull/879.

<img width="1012" alt="Screen Shot 2023-06-06 at 10 02 14 PM" src="https://github.com/casper-network/docs/assets/4185994/0aeffcec-e89c-45d1-962f-def4bc375831">

**Comment by ipopescu** [comment]
Hi @RitaMAllenCA, let's keep this open as a reminder to test this functionality. I am waiting for a 1.5 build to go into an integration testing environment or on Testnet.

**Comment by ipopescu** [comment]
Here is the account used for testing this functionality: https://integration.cspr.live/account/01360af61b50cdcb7b92cffe2c99315d413d34ef77fadee0c105cc4f1d4120f986.
Here is the redelgate using the system auction:
https://integration.cspr.live/deploy/a10872dad686b2bde4c3d5a57f571a8b0a82cc6efc822e43c08f82a2fe8b83aa
Here is the redelegate using the "redelegate.wasm" contract:
https://integration.cspr.live/deploy/6dd58de33a139a5aa92093b102e62f41926b805b08aa46a758e588ea6963d7fd
