### ISSUE TITLE
Update videos for the new counter repository

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#900]
- [ ] Re-record the content
- [ ] Edit the videos
- [ ] Send them to the Association for branding and upload
- [ ] Ask the Association to update all references to the new counter contract on YouTube 

- [ ] Does this video need to be reshot based on the new doc structure?

**Comment by RitaMAllenCA** [comment]
need to be reviewed with the docs team and possibly Karan.  May need to update all videos based on the new structure look.

**Comment by ipopescu** [comment]
Most video content and scripts are still applicable, but the order in the documentation has changed and doesn't match the order in the YouTube playlist. I have discussed this with the team, and we all agree that this is ok; we don’t want to invest in additional video production until we get further feedback from the Association. 
The only update needed is for the video that points to the contract vs. session diagram. Once we have a new diagram, we should update the video. All this is captured in card #108.
We can close this card.
