### ISSUE TITLE
Gap Analysis on curriculum documentation

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#901]
"Dust off" the curriculum work - likely old and stale.  

Deliverable - set of updates that need to happen.

**Comment by ShalmaliCL** [comment]
Gap analysis is done and created [the curriculum outline](https://casperlabs.atlassian.net/l/cp/L0H5EyYo). Upcoming work related to curriculum development will be created as a part of [this card](https://github.com/casper-network/docs/issues/978).

CC: @ACStoneCL
