### ISSUE TITLE
Improve testing section

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#91]
The testing section needs some additional details and examples (request from Medha).

Talk about 2 layers of testing. 
- [x] #423
- [x] #424

Note: The 2 layers of testing have been split into two sub-stories.

Contract authors should use assertions and watches to ensure that their contracts are correct.
The final round of testing is indeed to deploy to a network, and observe the events, error messages, etc...
Examples: https://github.com/casper-ecosystem/kv-storage-contract

**Comment by devendran-m** [comment]
Associated issues were closed as on 27th May'22, so closing this epic.
