### ISSUE TITLE
Document named keys & entry points in Rust contracts

### ISSUE THREAD

**Issue by deuszex** [casper-network/docs#92]
Tutorial docs should explain the usage and benefit of named keys and entry points inside rust contracts, and what they are.
 [https://docs.rs/casper-types/latest/casper_types/contracts/struct.EntryPoint.html](url)
 [https://docs.rs/casper-types/latest/casper_types/contracts/type.NamedKeys.html](url)
 
 They are first mentioned in [https://docs.casperlabs.io/en/latest/dapp-dev-guide/tutorials/erc20/index.html](url), and should be done sooner.

add glossary entries for named keys and entry points

**Comment by ipopescu** [comment]
Removing the assignee so that the card remains open for prioritization and assignment to whom is available next sprint.

**Comment by devendran-m** [comment]
Addressed by overhauled Smart Contract documentation tickets #283

**Comment by ipopescu** [comment]
@devendran-m @darthsiroftardis, the request for this card has not been addressed in epic #283--so I have reopened the card. We need to have a small entry introducing what named keys are and why we use them, or how to use them. If you search the docs, you'll see that we don't have a good intro to this.
