### ISSUE TITLE
resources/changelog

### ISSUE THREAD

**Issue by Adrian-Wrona** [casper-network/docs#928]

**Comment by ipopescu** [comment]
@Adrian-Wrona, do you still need this issue? I see only [one issue](https://github.com/casper-network/docs-new/issues/107) for a changelog in docs-new, and it's closed.

**Comment by ipopescu** [comment]
Closing as discussed with @Adrian-Wrona. 
Also, IInstead of a changelog, we have the [PR history]( https://github.com/casper-network/docs/issues?q=is%3Aissue+is%3Aclosed).
