### ISSUE TITLE
Tutorial for the key-value contract

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#94]
Create a tutorial for the key-value contract/

1. Understand how to do this
2. Create the written tutorial and update this link: https://docs.casperlabs.io/en/latest/dapp-dev-guide/tutorials/kv-storage-tutorial.html
3. Peer review

**Comment by ipopescu** [comment]
I think we need to close this, @devendran-m, it looks like we archived this contract.

**Comment by devendran-m** [comment]
> I think we need to close this, @devendran-m, it looks like we archived this contract.

Hi @ipopescu , I am going to check this with Zoltan/Karan and Dmitry as there is a PR with comments that need addressing.

**Comment by ipopescu** [comment]
Won't do. @RitaMAllenCA we need to follow up with you to see if we need to revamp the contract; that contract would have documentation.
