### ISSUE TITLE
Gap analysis of node operator documentation

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#948]
Deliverable: list of gaps we can use to create tickets for future work.  Adding all the information here:
https://casperlabs.atlassian.net/wiki/spaces/DEVEXP/pages/1883537409/Operator+Documentation+Gap+Analysis

**Comment by ipopescu** [comment]
I have completed the analysis, and we can create new tickets to enhance the operator documentation based on [this confluence page](https://casperlabs.atlassian.net/wiki/spaces/DEVEXP/pages/1883537409/Operator+Documentation+Gap+Analysis).
