### ISSUE TITLE
Review "account hash" usage

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#95]
In many places, we use account address instead of account hash. Review the proper usage and update the docs.

**Comment by RitaMAllenCA** [comment]
@ipopescu please estimate for sprint entry.  I do not know if we will put it in the sprint, but please estimate anyway. thank you

**Comment by ipopescu** [comment]
Let's close this card, as it is already addressed in https://github.com/casper-network/docs/issues/404.

**Comment by ipopescu** [comment]
Actually, re-opening to break down my tasks.

**Comment by ipopescu** [comment]
This is on my radar and it's linked to #404.

**Comment by ipopescu** [comment]
I will address this as part of #404.
