### ISSUE TITLE
Create and propose a new curriculum outline

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#950]
deliverable is a final draft of the outline, fully reviewed and aligned.

**Comment by ramujin** [comment]
The first outline is located on [this confluence page](https://casperlabs.atlassian.net/wiki/spaces/DEVEXP/pages/1877966857/Casper+Course+Outline+Draft+WORK+IN+PROGRESS).

I still need to sync up with Adam, Iulia, and Karan to incorporate their feedback before we can call this task complete.

**Comment by ShalmaliCL** [comment]
The review is completed. Upcoming work related to curriculum development will be created as a part of [this card.](https://github.com/casper-network/docs/issues/978)

CC: @ACStoneCL @ipopescu
