### ISSUE TITLE
State required CPU

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#975]
As we see a variety of people in all regions across the world run our node, we increasingly run into more exotic hardware configurations. An error that can occur is running the node software on a hardware platform that is not supported, e.g. by the CPU lacking support for a subset of the required instruction set.
This has already manifested (https://casper-labs-team.slack.com/archives/C015VHEF532/p1678981169969509), but for clarity's sake we should analyze the binaries we ship using a suitable tool to detect the instruction set, then add a test that ensures this requirement does not change. Finally, this should be featured somewhat prominently in the docs or a FAQ, ideally containing the typical kernel error message and a reference to core dumps, so that it can be found by searching

**Comment by ACStoneCL** [comment]
Currently blocked by [casper-node #3767](https://app.zenhub.com/workspaces/engineering-l1-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/3767) and [casper-node #3768](https://app.zenhub.com/workspaces/engineering-l1-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/3768).

**Comment by ACStoneCL** [comment]
No longer blocked, pertinent information can be [found here.](https://casper-labs-team.slack.com/archives/C0135SDEGUC/p1681979258720039).
