### ISSUE TITLE
Move the FAQs to the support portal

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#977]
- ask SRE to populate the [support portal ](https://support.casperlabs.io/hc/en-gb)first (check-in late next week or the week of March 27)
- then remove the FAQs from the docs and add a link to the support portal

**Comment by cryofracture** [comment]
@ipopescu all current FAQ items have been populated on the support portal.

**Comment by ipopescu** [comment]
@cryofracture, could you also check this source of FAQs to see if there is anything useful: https://docs.cspr.community/docs/faq-validator.html?
