### ISSUE TITLE
Create Tickets to Track Work on Curriculum Development

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#978]
Using the [Casper Course Outline](https://casperlabs.atlassian.net/wiki/spaces/DEVEXP/pages/1877966857/Casper+Course+Outline+Draft+WORK+IN+PROGRESS) as developed, create a series of tickets to track work for the first several modules within an over-arcing Epic for the entire course.

**Comment by ShalmaliCL** [comment]
Created below tickets to track work for the course:
https://github.com/casper-network/docs/issues/1013
https://github.com/casper-network/docs/issues/1014
https://github.com/casper-network/docs/issues/1015
https://github.com/casper-network/docs/issues/1016
https://github.com/casper-network/docs/issues/1017

@ACStoneCL - Could you please help create the Epic for this?
Thank you!

**Comment by ShalmaliCL** [comment]
Epic is created https://github.com/casper-network/docs/issues/1022
