### ISSUE TITLE
Identify Videos that need to be Updated in the Counter Repo

### ISSUE THREAD

**Issue by ACStoneCL** [casper-network/docs#983]
- [ ] Identify videos that need to be updated
- [ ] ~Create new scripts to be recorded when the docs structure stabilizes [ticket #900](https://github.com/casper-network/docs/issues/900)~ Moved this to a new card (#1084). The docs structure needs to stabilize before creating the scripts.

**Comment by ipopescu** [comment]
I broke this down into 2 parts and created card #1084. The docs need to stabilize before creating scripts.

**Comment by ipopescu** [comment]
@ACStoneCL @ramujin @ShalmaliCL, I have reviewed all the videos and left some [notes in Confluence](https://casperlabs.atlassian.net/wiki/spaces/DEVEXP/pages/1808891913/Videos+for+Writing+On-Chain+Code). 
All videos and scripts are still applicable, but the order in the documentation has changed and doesn't match the order in the YouTube playlist. I think this is ok, but I'd love to discuss this with you too on a brief call. 
Also, in our discussion, we can review cards #900 and #1084, which can be closed.
