### ISSUE TITLE
Update branding and company name for node 1.6

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#989]
We should update any images in READMEs and in links (e.g. html_favicon_url and html_logo_url). We should also update the name "CasperLabs" to "Casper Labs" throughout the code (e.g. in doc comments, READMEs, Cargo.toml files)

**Comment by RitaMAllenCA** [comment]
![Casper_Wordmark_Red_RGB](https://github.com/casper-network/docs/assets/115029729/5b476d35-8682-47cb-9cae-8550d039d104)
![Casper_Wordmark_White_RGB](https://github.com/casper-network/docs/assets/115029729/f6610f11-1f4a-4d72-b0e1-58bb85a377ba)
![Casper_Wordmark_Black_RGB](https://github.com/casper-network/docs/assets/115029729/9ecc62e4-7f7a-4f4e-918f-fcf56f6852f0)

**Comment by ACStoneCL** [comment]
It looks like this has a [PR already staged](https://github.com/casper-network/casper-node/pull/3837), but I will use the ticket as an opportunity to push for merging and finishing out that PR.
